-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: accepted-research-change-status-cleanup-2026-07-18
-- Generated at: 2026-07-19T03:34:16.565642+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Applied and accepted source-refresh batch should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'event-candidate-replay-a-source-refresh-2026-07-17';
-- Reason: Applied and accepted Batch A identity/status correction should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'identity-status-batch-a-game-chest-irvine-2026-07-17';
-- Reason: Applied and accepted Batch A identity/status correction should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'identity-status-batch-a-kingslayer-2026-07-17';
-- Reason: Applied and accepted Batch A identity/status correction should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'identity-status-batch-a-krazy-honeypot-2026-07-17';
-- Reason: Applied and accepted Batch A identity/status correction should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'identity-status-batch-a-projectccg-2026-07-17';
-- Reason: Applied and accepted Batch A identity/status correction should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'identity-status-batch-a-shuffle-cut-realm-2026-07-17';
-- Reason: Applied and accepted evaluation implications pass should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'evaluation-implications-replay-a-2026-07-17';
-- Reason: Applied and accepted evidence backfill should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'review-source-evidence-backfill-2026-07-17';
-- Reason: Applied and accepted nearby assessment pass should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'nearby-thin-discovery-assessment-pass-2026-07-17';
-- Reason: Applied and accepted unresolved-discovery pass should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'unresolved-discovery-assessment-pass-2026-07-17';
-- Reason: Applied and accepted planning-quality assessment pass should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'change-planning-quality-places-assessment-pass-a-2026-07-17';
-- Reason: Applied and accepted WPN-led assessment pass should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'wpn-led-planning-assessment-pass-c-2026-07-17';
-- Reason: Applied and accepted status-conflict assessment pass should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'status-conflict-event-assessment-pass-d-2026-07-17';
-- Reason: Applied and accepted corrected source coverage batch should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'corrected-source-coverage-batch-e-2026-07-17';
-- Reason: Applied and accepted Finch corrected event backfill should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'finch-sparrow-corrected-event-backfill-2026-07-18';
-- Reason: Applied and accepted Shadow/TK/Games For Meeple correction should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'shadow-tk-games-for-meeple-event-correction-2026-07-18';
-- Reason: Applied and accepted GX/Otaku/LVLUP event completion should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'gx-otaku-lvlup-event-completion-2026-07-18';
-- Reason: Applied and accepted Turn Zero/Core/Aki/ProjectCCG event completion should not remain labeled as pending in Updates.
update public.research_changes set review_status = 'accepted' where id is not distinct from 'change-2026-07-18-turnzero-core-aki-projectccg-event-completion';

-- Post-write row-count verification:
select * from (
  select 'research_changes' as table_name, count(*)::bigint as row_count from public.research_changes
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;
