-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: finch-kingslayer-cardboard-event-completion-2026-07-18
-- Generated at: 2026-07-18T23:19:07.326175+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Fresh Wizards/EventLink pull inspected for Finch and Sparrow Games.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-6718';
-- Reason: Fresh Wizards/EventLink pull inspected for Kingslayer Games - Fountain Valley.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-7819';
-- Reason: Fresh Wizards/EventLink pull inspected for Cardboard Games.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-17086';
-- Reason: Refresh existing Finch draft row with current WPN title, fee, and verification.
update public.event_series set title = 'Magic: the Gathering Draft Nights!', entry_fee = 28.0, details = 'Fresh Wizards/EventLink pull confirms recurring Wednesday 7:00 PM Magic draft nights at Finch and Sparrow Games with $28 entry. This remains a current limited-format planning lane.', last_verified = '2026-07-18', venue_id = 'finch-sparrow' where id is not distinct from 'finch-sparrow-booster-draft-standard-sets';
-- Reason: Attach fresh WPN provenance to the updated Finch draft row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6718', 'finch-sparrow-booster-draft-standard-sets', null, 'fresh Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Refresh existing Finch Tuesday Modern row with current WPN fee and verification.
update public.event_series set entry_fee = 15.0, details = 'Fresh Wizards/EventLink pull confirms recurring Tuesday 7:00 PM Modern Kombat at Finch and Sparrow Games with $15 entry. This is lower personal priority than Commander/draft/prerelease but supports Finch''s broad active Magic footprint.', last_verified = '2026-07-18', venue_id = 'finch-sparrow' where id is not distinct from 'finch-sparrow-modern-kombat';
-- Reason: Attach fresh WPN provenance to the updated Finch Tuesday Modern row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6718', 'finch-sparrow-modern-kombat', null, 'fresh Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Clarify an existing generic Finch FNM row using current WPN event title/format.
update public.event_series set title = 'Friday Modern Kombat', format = 'Modern', event_type = 'constructed', bracket = 'all', entry_fee = 15.0, confidence = 'high', details = 'Fresh Wizards/EventLink pull clarifies Finch''s Friday 7:00 PM Magic/FNM lane as Modern Kombat with $15 entry. This replaces the prior generic FNM label; it is useful as Magic-program context but is lower personal priority than Commander, draft, or prerelease.', last_verified = '2026-07-18', venue_id = 'finch-sparrow' where id is not distinct from 'finch-sparrow-fnm-at-finch-and-sparrow';
-- Reason: Attach fresh WPN provenance to the clarified Finch Friday Modern row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6718', 'finch-sparrow-fnm-at-finch-and-sparrow', null, 'fresh Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog current source-supported Finch Pauper event signal missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('finch-sparrow-pauper-night-1-19-00', 'finch-sparrow', 'Pauper Night!', 'Pauper', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":1,"startTime":"19:00"}'::jsonb, '19:00', '2026-07-20', '2026-08-03', 10.0, 'USD', 'Fresh Wizards/EventLink pull lists Monday 7:00 PM Pauper Night at Finch and Sparrow Games with $10 entry, visible for July 20, July 27, and August 3, 2026. Treat as a short-run current Magic signal rather than an indefinite recurring row.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed Finch Pauper row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6718', 'finch-sparrow-pauper-night-1-19-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Avoid leaving an unsupported open-ended Finch Standard row visible in the planning calendar.
update public.event_series set event_status = 'inactive', end_date = '2026-07-18', details = 'Previously cataloged from Finch''s official event calendar as Monday 7:00 PM MTG Standard Constructed. Fresh Wizards/EventLink pull on July 18, 2026 did not surface this row; the current Monday WPN evidence instead shows cEDH Workshop and short-run Pauper Night. Retired from active planning pending future official replay.', last_verified = '2026-07-18', venue_id = 'finch-sparrow' where id is not distinct from 'finch-sparrow-mtg-standard-constructed';
-- Reason: Fresh WPN pull reconfirmed Saturday Commanderfest at 2:30 PM.
update public.event_series set last_verified = '2026-07-18', venue_id = 'finch-sparrow' where id is not distinct from 'finch-sparrow-commanderfest-6-14-30';
-- Reason: Attach fresh WPN provenance to the reconfirmed Finch Commanderfest row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6718', 'finch-sparrow-commanderfest-6-14-30', null, 'fresh Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Fresh WPN pull reconfirmed Wednesday Commander Slay Pass for Kingslayer Fountain Valley.
update public.event_series set last_verified = '2026-07-18', venue_id = 'kingslayer-games-fountain-valley' where id is not distinct from 'kingslayer-games-fountain-valley-fountain-valley-wednesday-m';
-- Reason: Attach fresh WPN provenance to the reconfirmed Kingslayer Wednesday Commander row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-7819', 'kingslayer-games-fountain-valley-fountain-valley-wednesday-m', null, 'fresh Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Fresh WPN pull reconfirmed Friday Commander Slay Pass for Kingslayer Fountain Valley.
update public.event_series set last_verified = '2026-07-18', venue_id = 'kingslayer-games-fountain-valley' where id is not distinct from 'kingslayer-games-fountain-valley-fountain-valley-mtg-fnm-com';
-- Reason: Attach fresh WPN provenance to the reconfirmed Kingslayer Friday Commander row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-7819', 'kingslayer-games-fountain-valley-fountain-valley-mtg-fnm-com', null, 'fresh Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported Kingslayer Fountain Valley Standard row missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('kingslayer-fv-sunday-standard-0-12-00', 'kingslayer-games-fountain-valley', 'Fountain Valley MTG Standard Sunday', 'Standard', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":0,"startTime":"12:00"}'::jsonb, '12:00', '2026-07-19', '2026-07-26', 10.0, 'USD', 'Fresh Wizards/EventLink pull lists Kingslayer Games - Fountain Valley Sunday 12:00 PM Standard with $10 entry, visible July 19 and July 26, 2026. Treat as a short-run current Magic signal unless future official evidence extends it.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed Kingslayer Standard row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-7819', 'kingslayer-fv-sunday-standard-0-12-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported Kingslayer Fountain Valley Pauper row missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('kingslayer-fv-pauper-tuesday-2-18-30', 'kingslayer-games-fountain-valley', 'Fountain Valley MTG Pauper Tuesday', 'Pauper', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":2,"startTime":"18:30"}'::jsonb, '18:30', '2026-07-21', '2026-07-28', 10.0, 'USD', 'Fresh Wizards/EventLink pull lists Kingslayer Games - Fountain Valley Tuesday 6:30 PM Pauper with $10 entry, visible July 21 and July 28, 2026. Treat as a short-run current Magic signal unless future official evidence extends it.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed Kingslayer Pauper row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-7819', 'kingslayer-fv-pauper-tuesday-2-18-30', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported Kingslayer Fountain Valley Modern row missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('kingslayer-fv-fnm-modern-5-18-30', 'kingslayer-games-fountain-valley', 'Fountain Valley MTG FNM Modern', 'Modern', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"18:30"}'::jsonb, '18:30', '2026-07-24', '2026-07-31', 10.0, 'USD', 'Fresh Wizards/EventLink pull lists Kingslayer Games - Fountain Valley Friday 6:30 PM FNM Modern with $10 entry, visible July 24 and July 31, 2026. Treat as a short-run current Magic signal unless future official evidence extends it.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed Kingslayer Modern row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-7819', 'kingslayer-fv-fnm-modern-5-18-30', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported dated Kingslayer Fountain Valley draft missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('kingslayer-fv-outlaws-draft-2026-07-24', 'kingslayer-games-fountain-valley', 'Fountain Valley MTG Outlaws of Thunder Junction Booster Draft', 'Draft', 'draft', 'all', null, '18:30', '2026-07-24', null, 25.0, 'USD', 'Fresh Wizards/EventLink pull lists a Friday, July 24, 2026 6:30 PM Outlaws of Thunder Junction booster draft at Kingslayer Games - Fountain Valley with $25 entry.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed Kingslayer Outlaws draft row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-7819', 'kingslayer-fv-outlaws-draft-2026-07-24', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported dated Kingslayer Fountain Valley draft missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('kingslayer-fv-tarkir-draft-2026-07-31', 'kingslayer-games-fountain-valley', 'Fountain Valley MTG Tarkir: Dragonstorm Booster Draft', 'Draft', 'draft', 'all', null, '18:30', '2026-07-31', null, 20.0, 'USD', 'Fresh Wizards/EventLink pull lists a Friday, July 31, 2026 6:30 PM Tarkir: Dragonstorm booster draft at Kingslayer Games - Fountain Valley with $20 entry. Event copy notes 6:00 PM check-in and 6:30 PM start.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed Kingslayer Tarkir draft row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-7819', 'kingslayer-fv-tarkir-draft-2026-07-31', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Fresh WPN pull reconfirmed Friday CBG Commander Night.
update public.event_series set last_verified = '2026-07-18', venue_id = 'cardboard-games' where id is not distinct from 'cardboard-games-cbg-commander-night-5-19-00';
-- Reason: Fresh WPN pull reconfirmed Monday CBG Marvel Superheroes Draft.
update public.event_series set last_verified = '2026-07-18', venue_id = 'cardboard-games' where id is not distinct from 'cardboard-games-cbg-marvel-superheroes-draft-1-19-00';
-- Reason: Create a visible Updates marker for the proposed event-completion batch.
insert into public.research_changes (id, detected_at, change_type, entity_type, entity_id, summary, review_status) values ('chg-2026-07-18-finch-kingslayer-cardboard-event-completion', '2026-07-18T12:45:00-07:00', 'new_event', 'event', 'finch-kingslayer-cardboard-event-completion', 'Fresh Wizards/EventLink completion pass added or refreshed current Magic event coverage for Finch and Sparrow, Kingslayer Fountain Valley, and Cardboard, including non-Commander formats where source-supported.', 'proposed');

-- Post-write row-count verification:
select * from (
  select 'event_series' as table_name, count(*)::bigint as row_count from public.event_series
union all
  select 'event_sources' as table_name, count(*)::bigint as row_count from public.event_sources
union all
  select 'research_changes' as table_name, count(*)::bigint as row_count from public.research_changes
union all
  select 'sources' as table_name, count(*)::bigint as row_count from public.sources
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;
