-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: game-cellar-nextgen-gametime-event-assessment-pass-2026-07-18
-- Generated at: 2026-07-18T14:26:23.327111+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Wizards/EventLink export contains current July-September 2026 The Game Cellar Commander Party and Hobbit prerelease records.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-13567';
-- Reason: Wizards/EventLink export contains current July-October 2026 Next-Gen Magic rows beyond the already captured Wednesday Commander series.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-9747';
-- Reason: Wizards/EventLink export still supports It's GameTime Sunday Casual Commander rows in the checked July-August 2026 window.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-9054';
-- Reason: Next-Gen's official site links this Discord as a community route. The route is useful for future turnout, LFG, proxy, solo-arrival, and event-reliability replay, but Discord content was not inspected in this pass.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-nextgen-discord-route-2026-07-18', 'Next-Gen Games official Discord route', 'https://discord.com/invite/DxfmsR8', 'community', 'current', '2026-07-18');
-- Reason: Make the official community route visible as Evidence without overclaiming inspected Discord content.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'next-gen-games', 'src-nextgen-discord-route-2026-07-18', 'official Discord route captured / content replay TBD');
-- Reason: Catalog source-supported prerelease/sealed coverage that was missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('game-cellar-hobbit-prerelease-2026', 'the-game-cellar', 'The Hobbit Prerelease', 'Sealed', 'prerelease', 'all', 'null'::jsonb, null, '2026-08-07', '2026-08-12', 35.0, 'USD', 'Wizards/EventLink lists eight finite The Hobbit prerelease sealed occurrences at The Game Cellar from August 7-12, 2026. Event copy says pack prizing is based on participation.', 'high', 'active', '2026-07-18');
-- Reason: Make a clear dated Commander Party visible for planning.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('game-cellar-marvel-super-heroes-commander-party-2026-07-31', 'the-game-cellar', 'Marvel Super Heroes Commander Party', 'Commander', 'special', 'all', 'null'::jsonb, '19:00', '2026-07-31', '2026-07-31', 5.0, 'USD', 'Wizards/EventLink lists a Friday, July 31, 2026 Marvel Super Heroes Commander Party at The Game Cellar at 7:00 PM with $5 entry.', 'high', 'active', '2026-07-18');
-- Reason: Make finite Commander Party dates visible without modeling them as weekly recurrence.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('game-cellar-hobbit-commander-party-2026', 'the-game-cellar', 'The Hobbit Commander Party', 'Commander', 'special', 'all', 'null'::jsonb, '19:00', '2026-08-21', '2026-09-18', 5.0, 'USD', 'Wizards/EventLink lists The Hobbit Commander Party occurrences at The Game Cellar on August 21 and September 18, 2026 at 7:00 PM with $5 entry.', 'high', 'active', '2026-07-18');
-- Reason: Catalog a current weekly draft lane missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-saturday-draft', 'next-gen-games', 'Saturday Draft', 'Draft', 'draft', 'all', '{"frequency":"weekly","dayOfWeek":6,"startTime":"12:00"}'::jsonb, '12:00', '2026-07-18', null, 25.0, 'USD', 'Wizards/EventLink lists recurring Saturday Draft at Next-Gen Games at 12:00 PM, with $25 entry and 32-player capacity in the checked export window.', 'high', 'active', '2026-07-18');
-- Reason: Catalog a second current Saturday draft lane missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-saturday-afternoon-draft', 'next-gen-games', 'Saturday Afternoon Draft', 'Draft', 'draft', 'all', '{"frequency":"weekly","dayOfWeek":6,"startTime":"16:00"}'::jsonb, '16:00', '2026-07-18', null, 25.0, 'USD', 'Wizards/EventLink lists recurring Saturday Afternoon Draft at Next-Gen Games at 4:00 PM, with $25 entry and 32-player capacity in the checked export window.', 'high', 'active', '2026-07-18');
-- Reason: Catalog a current constructed Magic lane for store-activity completeness.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-standard-showdown', 'next-gen-games', 'Standard Showdown', 'Standard', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":1,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-20', null, 5.0, 'USD', 'Wizards/EventLink lists recurring Monday Standard Showdown at Next-Gen Games at 7:30 PM with $5 entry in the checked export window.', 'high', 'active', '2026-07-18');
-- Reason: Catalog a current constructed Magic lane for store-activity completeness.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-legacy-thursday', 'next-gen-games', 'Legacy Thursday', 'Legacy', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":4,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-23', null, 5.0, 'USD', 'Wizards/EventLink lists recurring Legacy Thursday at Next-Gen Games at 7:30 PM with $5 entry and 32-player capacity in the checked export window.', 'high', 'active', '2026-07-18');
-- Reason: Catalog a current FNM/Modern constructed lane for store-activity completeness.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-friday-night-magic-modern', 'next-gen-games', 'Friday Night Magic Modern', 'Modern', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-24', null, 5.0, 'USD', 'Wizards/EventLink lists recurring Friday Night Magic Modern at Next-Gen Games at 7:30 PM with $5 entry in the checked export window.', 'high', 'active', '2026-07-18');
-- Reason: Make the clear current Sunday Commander signal visible while preserving the start-time ambiguity.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-all-day-sunday-commander', 'next-gen-games', 'All Day Sunday Commander', 'Commander', 'commander', 'all', '{"frequency":"weekly","dayOfWeek":0,"startTime":"11:00"}'::jsonb, '11:00', '2026-07-19', null, 5.0, 'USD', 'Wizards/EventLink lists All Day Sunday Commander at Next-Gen Games with $5 entry and 64-player capacity. The export''s local scheduled time renders as 11:00 PM, which conflicts with the all-day title and store hours. This row uses Next-Gen''s official Sunday opening time, 11:00 AM, as a planning proxy and records that assumption.', 'medium', 'active', '2026-07-18');
-- Reason: Make finite Commander specials visible without modeling them as weekly recurrence.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-two-headed-giant-commander-2026', 'next-gen-games', 'Two Headed Giant Commander', 'Commander', 'special', 'all', 'null'::jsonb, '12:00', '2026-07-26', '2026-08-30', 5.0, 'USD', 'Wizards/EventLink lists Two Headed Giant Commander specials at Next-Gen Games on July 26 and August 30, 2026 at 12:00 PM. The two records show different entry-fee amounts, so dated occurrences preserve the exact fee where known.', 'high', 'active', '2026-07-18');
-- Reason: Make a current dated Commander Party visible for planning.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('next-gen-marvel-super-heroes-commander-party-2026-08-02', 'next-gen-games', 'Marvel Super Heroes Commander Party', 'Commander', 'special', 'all', 'null'::jsonb, '12:00', '2026-08-02', '2026-08-02', 40.0, 'USD', 'Wizards/EventLink lists a Sunday, August 2, 2026 Marvel Super Heroes Commander Party at Next-Gen Games at 12:00 PM with $40 entry and 64-player capacity.', 'high', 'active', '2026-07-18');
-- Reason: Make a store-controlled recurring Friday Magic signal visible while preserving format uncertainty.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('its-gametime-friday-night-magic', 'it-s-gametime', 'Friday Night Magic', 'Magic', 'special', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"20:00"}'::jsonb, '20:00', '2026-07-24', null, null, 'USD', 'It''s GameTime''s official site lists Friday Night Magic at 8:00 PM. The site does not specify the format, registration, entry fee, or whether this appears in Wizards/EventLink, so keep this as a medium-confidence recurring FNM/Magic signal rather than normalizing it as Commander, draft, or sealed.', 'medium', 'active', '2026-07-18');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-07-14-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-07', '14:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136625 confirms The Hobbit Prerelease at The Game Cellar on Friday, August 7, 2026 at 2:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-07-19-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-07', '19:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136626 confirms The Hobbit Prerelease at The Game Cellar on Friday, August 7, 2026 at 7:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-08-12-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-08', '12:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136627 confirms The Hobbit Prerelease at The Game Cellar on Saturday, August 8, 2026 at 12:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-08-17-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-08', '17:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136628 confirms The Hobbit Prerelease at The Game Cellar on Saturday, August 8, 2026 at 5:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-09-12-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-09', '12:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136629 confirms The Hobbit Prerelease at The Game Cellar on Sunday, August 9, 2026 at 12:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-09-17-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-09', '17:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136630 confirms The Hobbit Prerelease at The Game Cellar on Sunday, August 9, 2026 at 5:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-12-14-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-12', '14:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136631 confirms The Hobbit Prerelease at The Game Cellar on Wednesday, August 12, 2026 at 2:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-prerelease-2026-08-12-19-00', 'game-cellar-hobbit-prerelease-2026', '2026-08-12', '19:00', null, 'single_source', 'confirmed', 35.0, null, 'Wizards/EventLink event 11136632 confirms The Hobbit Prerelease at The Game Cellar on Wednesday, August 12, 2026 at 7:00 PM.');
-- Reason: Add exact dated Commander Party occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-marvel-super-heroes-commander-party-2026-07-31-19-00', 'game-cellar-marvel-super-heroes-commander-party-2026-07-31', '2026-07-31', '19:00', null, 'single_source', 'confirmed', 5.0, null, 'Wizards/EventLink event 11136651 confirms Marvel Super Heroes Commander Party at The Game Cellar on Friday, July 31, 2026 at 7:00 PM.');
-- Reason: Add exact dated Commander Party occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-commander-party-2026-08-21-19-00', 'game-cellar-hobbit-commander-party-2026', '2026-08-21', '19:00', null, 'single_source', 'confirmed', 5.0, null, 'Wizards/EventLink event 11136657 confirms The Hobbit Commander Party at The Game Cellar on Friday, August 21, 2026 at 7:00 PM.');
-- Reason: Add exact dated Commander Party occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('game-cellar-hobbit-commander-party-2026-09-18-19-00', 'game-cellar-hobbit-commander-party-2026', '2026-09-18', '19:00', null, 'single_source', 'confirmed', 5.0, null, 'Wizards/EventLink event 11136659 confirms The Hobbit Commander Party at The Game Cellar on Friday, September 18, 2026 at 7:00 PM.');
-- Reason: Add exact dated Commander special occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('next-gen-two-headed-giant-commander-2026-07-26-12-00', 'next-gen-two-headed-giant-commander-2026', '2026-07-26', '12:00', null, 'single_source', 'confirmed', 5.0, null, 'Wizards/EventLink event 11270799 confirms Two Headed Giant Commander at Next-Gen Games on Sunday, July 26, 2026 at 12:00 PM.');
-- Reason: Add exact dated Commander special occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('next-gen-two-headed-giant-commander-2026-08-30-12-00', 'next-gen-two-headed-giant-commander-2026', '2026-08-30', '12:00', null, 'single_source', 'confirmed', 10.0, null, 'Wizards/EventLink event 11270800 confirms Two Headed Giant Commander at Next-Gen Games on Sunday, August 30, 2026 at 12:00 PM.');
-- Reason: Add exact dated Commander Party occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('next-gen-marvel-super-heroes-commander-party-2026-08-02-12-00', 'next-gen-marvel-super-heroes-commander-party-2026-08-02', '2026-08-02', '12:00', null, 'single_source', 'confirmed', 40.0, 64, 'Wizards/EventLink event 11081434 confirms Marvel Super Heroes Commander Party at Next-Gen Games on Sunday, August 2, 2026 at 12:00 PM.');
-- Reason: Attach WPN evidence to The Game Cellar Hobbit prerelease series.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-13567', 'game-cellar-hobbit-prerelease-2026', null, 'Wizards/EventLink finite prerelease evidence');
-- Reason: Attach WPN evidence to The Game Cellar Marvel Commander Party series.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-13567', 'game-cellar-marvel-super-heroes-commander-party-2026-07-31', null, 'Wizards/EventLink dated Commander Party evidence');
-- Reason: Attach WPN evidence to The Game Cellar Hobbit Commander Party series.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-13567', 'game-cellar-hobbit-commander-party-2026', null, 'Wizards/EventLink dated Commander Party evidence');
-- Reason: Attach WPN evidence to Next-Gen Saturday Draft.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-saturday-draft', null, 'Wizards/EventLink recurring draft evidence');
-- Reason: Attach WPN evidence to Next-Gen Saturday Afternoon Draft.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-saturday-afternoon-draft', null, 'Wizards/EventLink recurring draft evidence');
-- Reason: Attach WPN evidence to Next-Gen Standard Showdown.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-standard-showdown', null, 'Wizards/EventLink recurring Standard evidence');
-- Reason: Attach WPN evidence to Next-Gen Legacy Thursday.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-legacy-thursday', null, 'Wizards/EventLink recurring Legacy evidence');
-- Reason: Attach WPN evidence to Next-Gen Friday Night Magic Modern.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-friday-night-magic-modern', null, 'Wizards/EventLink recurring FNM Modern evidence');
-- Reason: Attach WPN evidence to Next-Gen Sunday Commander.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-all-day-sunday-commander', null, 'Wizards/EventLink recurring Commander evidence with planning-time caveat');
-- Reason: Attach WPN evidence to Next-Gen Two Headed Giant Commander.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-two-headed-giant-commander-2026', null, 'Wizards/EventLink dated Commander special evidence');
-- Reason: Attach WPN evidence to Next-Gen Marvel Commander Party.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9747', 'next-gen-marvel-super-heroes-commander-party-2026-08-02', null, 'Wizards/EventLink dated Commander Party evidence');
-- Reason: Attach official site schedule evidence to It's GameTime Friday Night Magic.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-itsgametime-official-schedule-2026-07-17', 'its-gametime-friday-night-magic', null, 'official site recurring FNM evidence');
-- Reason: Create a durable proposed update marker before any live write.
insert into public.research_changes (id, detected_at, change_type, entity_type, entity_id, summary, review_status) values ('game-cellar-nextgen-gametime-event-assessment-pass-2026-07-18', '2026-07-18T02:00:00-07:00', 'event_update', 'venue', 'next-gen-games', 'Proposed bounded event/assessment replay for The Game Cellar, Next-Gen Games, and It''s GameTime. The pass surfaces missing Game Cellar prerelease/Commander Party dates, Next-Gen draft/constructed/Commander special coverage, It''s GameTime Friday FNM, and a Next-Gen Discord route captured for later community replay.', 'proposed');

-- Post-write row-count verification:
select * from (
  select 'entity_sources' as table_name, count(*)::bigint as row_count from public.entity_sources
union all
  select 'event_occurrences' as table_name, count(*)::bigint as row_count from public.event_occurrences
union all
  select 'event_series' as table_name, count(*)::bigint as row_count from public.event_series
union all
  select 'event_sources' as table_name, count(*)::bigint as row_count from public.event_sources
union all
  select 'research_changes' as table_name, count(*)::bigint as row_count from public.research_changes
union all
  select 'sources' as table_name, count(*)::bigint as row_count from public.sources
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;
