-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: gx-otaku-lvlup-event-completion-2026-07-18
-- Generated at: 2026-07-18T18:24:18.615759+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Fresh Wizards/EventLink pull inspected for this event-completion pass.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-22276';
-- Reason: Fresh Wizards/EventLink pull inspected for this event-completion pass.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-18939';
-- Reason: Fresh Wizards/EventLink pull inspected for this event-completion pass.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-15152';
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('gxgamers-wednesday-standard-showdown-3-19-00', 'gxgamers', 'Wednesday Standard Showdown', 'Standard', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":3,"startTime":"19:00"}'::jsonb, '19:00', '2026-07-22', null, 10.0, 'USD', 'Fresh Wizards/EventLink pull lists recurring Wednesday 7:00 PM Standard Showdown at GXGAMERS with $10 entry. Event copy describes participation packs, prize support, and top-3/4 prizing depending on player count.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-22276', 'gxgamers-wednesday-standard-showdown-3-19-00', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('gxgamers-the-hobbit-prerelease-2026-08-07', 'gxgamers', 'GXGAMERS - The Hobbit Prerelease', 'Sealed', 'prerelease', 'all', null, '18:00', '2026-08-07', null, 45.0, 'USD', 'Fresh Wizards/EventLink pull lists Friday, August 7, 2026 The Hobbit prerelease at GXGAMERS. Check-in is 6:00 PM, deckbuilding 6:30 PM, Swiss starts 7:00 PM, with prerelease kit participation and per-win booster prizing.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-22276', 'gxgamers-the-hobbit-prerelease-2026-08-07', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('otaku-vault-the-hobbit-prerelease-2026-08-07-13-30', 'otaku-vault', 'The Hobbit @ Otaku Vault Prerelease', 'Sealed', 'prerelease', 'all', null, '13:30', '2026-08-07', null, 35.0, 'USD', 'Fresh Wizards/EventLink pull lists Friday, August 7, 2026 1:30 PM The Hobbit prerelease at Otaku Vault, described as prerelease Part 1.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18939', 'otaku-vault-the-hobbit-prerelease-2026-08-07-13-30', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('otaku-vault-the-hobbit-prerelease-2026-08-07-19-00', 'otaku-vault', 'The Hobbit @ Otaku Vault Prerelease', 'Sealed', 'prerelease', 'all', null, '19:00', '2026-08-07', null, 35.0, 'USD', 'Fresh Wizards/EventLink pull lists Friday, August 7, 2026 7:00 PM The Hobbit prerelease at Otaku Vault, described as a casual three-round Swiss prerelease.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18939', 'otaku-vault-the-hobbit-prerelease-2026-08-07-19-00', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('otaku-vault-the-hobbit-commander-party-2026-08-21', 'otaku-vault', 'The Hobbit @ Otaku Vault Commander Party', 'Commander', 'commander', 'all', null, '19:00', '2026-08-21', null, 10.0, 'USD', 'Fresh Wizards/EventLink pull lists Friday, August 21, 2026 7:00 PM The Hobbit Commander Party at Otaku Vault, described as a story-inspired Commander event.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18939', 'otaku-vault-the-hobbit-commander-party-2026-08-21', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('otaku-vault-two-headed-giant-commander-2026-08-28', 'otaku-vault', 'Two Headed Giant Commander @Otaku Vault', 'Commander', 'commander', 'all', null, '19:00', '2026-08-28', null, 5.0, 'USD', 'Fresh Wizards/EventLink pull lists Friday, August 28, 2026 7:00 PM Two-Headed Giant Commander at Otaku Vault, with copy inviting players to bring a friend or link up with another player.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18939', 'otaku-vault-two-headed-giant-commander-2026-08-28', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('lvlup-gaming-tcg-the-hobbit-prerelease-2026-08-07', 'lvlup-gaming-tcg', 'The Hobbit Prerelease', 'Sealed', 'prerelease', 'all', null, '19:30', '2026-08-07', null, 35.0, 'USD', 'Fresh Wizards/EventLink pull lists Friday, August 7, 2026 7:30 PM The Hobbit prerelease at LVLUP GAMING TCG with play-booster prize support.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-15152', 'lvlup-gaming-tcg-the-hobbit-prerelease-2026-08-07', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('lvlup-gaming-tcg-an-unexpected-crafting-party-2026-08-14', 'lvlup-gaming-tcg', 'An Unexpected Crafting Party', 'Magic', 'special', 'all', null, '19:30', '2026-08-14', null, 0.0, 'USD', 'Fresh Wizards/EventLink pull lists Friday, August 14, 2026 7:30 PM An Unexpected Crafting Party at LVLUP GAMING TCG as a free Magic special event.', 'medium', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-15152', 'lvlup-gaming-tcg-an-unexpected-crafting-party-2026-08-14', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('lvlup-gaming-tcg-two-headed-giant-commander-the-hobbit-2026-08-18', 'lvlup-gaming-tcg', 'Two Headed Giant Commander The Hobbit', 'Commander', 'commander', 'all', null, '19:30', '2026-08-18', null, 25.0, 'USD', 'Fresh Wizards/EventLink pull lists Tuesday, August 18, 2026 7:30 PM Two-Headed Giant Commander The Hobbit at LVLUP GAMING TCG, with prizing TBD.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-15152', 'lvlup-gaming-tcg-two-headed-giant-commander-the-hobbit-2026-08-18', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('lvlup-gaming-tcg-the-hobbit-commander-party-2026-08-25', 'lvlup-gaming-tcg', 'The Hobbit Commander Party', 'Commander', 'commander', 'all', null, '19:30', '2026-08-25', null, 10.0, 'USD', 'Fresh Wizards/EventLink pull lists Tuesday, August 25, 2026 7:30 PM The Hobbit Commander Party at LVLUP GAMING TCG, with prizing TBD.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-15152', 'lvlup-gaming-tcg-the-hobbit-commander-party-2026-08-25', null, 'Wizards/EventLink evidence');
-- Reason: Catalog source-supported future Magic event missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('lvlup-gaming-tcg-magic-presents-heart-of-the-mountain-2026-09-08', 'lvlup-gaming-tcg', 'Magic Presents: Heart of the Mountain', 'Commander', 'commander', 'all', null, '19:30', '2026-09-08', null, 10.0, 'USD', 'Fresh Wizards/EventLink pull lists Tuesday, September 8, 2026 7:30 PM Magic Presents: Heart of the Mountain at LVLUP GAMING TCG, with promos provided for entry.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to the proposed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-15152', 'lvlup-gaming-tcg-magic-presents-heart-of-the-mountain-2026-09-08', null, 'Wizards/EventLink evidence');
-- Reason: Capture official social/community routing, including Discord route, without claiming content replay.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-gxgamers-linktree-2026-07-18', 'GXGAMERS Linktree with Discord and social routes', 'https://linktr.ee/gxgamersla', 'community', 'current', '2026-07-18');
-- Reason: Make GX community route visible as evidence.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'gxgamers', 'src-gxgamers-linktree-2026-07-18', 'official social/community route captured; Discord content replay TBD');
-- Reason: Capture official-site Discord/Instagram route without claiming content replay.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-otaku-vault-discord-route-2026-07-18', 'Otaku Vault official site Discord route', 'https://www.otakuvault.la/shop', 'community', 'current', '2026-07-18');
-- Reason: Make Otaku community route visible as evidence.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'otaku-vault', 'src-otaku-vault-discord-route-2026-07-18', 'official Discord/Instagram route captured; content replay TBD');
-- Reason: Reflect broader current Magic calendar while preserving personal-fit cautions.
update public.venues set last_verified = '2026-07-18', assessment_notes = 'GXGAMERS remains a legitimate but situational Pico-Union multi-TCG option. Fresh Wizards/EventLink confirms Monday, Thursday, and Saturday Commander, and adds Wednesday Standard Showdown plus an August 7 Hobbit prerelease. Linktree exposes Discord and social routes for future community replay. The upside is reliable multi-night Magic coverage; the caution remains distance, parking, paid/prize structure, and the no-proxy Commander language.' where id is not distinct from 'gxgamers';
-- Reason: Reflect missing special-event coverage and community-route visibility.
update public.venues set last_verified = '2026-07-18', assessment_notes = 'Otaku Vault is more Magic-relevant than a single Friday Commander row suggested. Fresh Wizards/EventLink confirms Friday Commander and adds two August 7 Hobbit prerelease times, an August 21 Hobbit Commander Party, and an August 28 Two-Headed Giant Commander event. Official site routes to Instagram and Discord, but those community surfaces still need content replay before promoting Otaku as a strong personal fit.' where id is not distinct from 'otaku-vault';
-- Reason: Reflect broader current Magic calendar while preserving reliability caution.
update public.venues set last_verified = '2026-07-18', assessment_notes = 'LVLUP GAMING TCG has more current Magic activity than the older reliability-cautioned note alone suggested. Fresh Wizards/EventLink confirms Tuesday and Friday Commander and adds Hobbit prerelease, Magic Presents, Two-Headed Giant Commander, and Commander Party specials in August/September 2026. The added events should be visible, but the prior caution remains: because a previous report described arriving for a Companion-listed event and finding the store apparently closed, a first visit should still be same-day confirmed.' where id is not distinct from 'lvlup-gaming-tcg';
-- Reason: Create durable proposed update marker.
insert into public.research_changes (id, detected_at, change_type, entity_type, entity_id, summary, review_status) values ('gx-otaku-lvlup-event-completion-2026-07-18', '2026-07-18T11:30:00-07:00', 'research_update', 'venue', 'gxgamers', 'Proposed event-completion pass for GXGAMERS, Otaku Vault, and LVLUP after fresh Wizards/EventLink pull. Adds missing Standard, prerelease, Commander Party, Two-Headed Giant, and Magic Presents rows; captures GX/Otaku community routes as content-replay TBD; preserves personal-fit cautions.', 'proposed');

-- Post-write row-count verification:
select * from (
  select 'entity_sources' as table_name, count(*)::bigint as row_count from public.entity_sources
union all
  select 'event_series' as table_name, count(*)::bigint as row_count from public.event_series
union all
  select 'event_sources' as table_name, count(*)::bigint as row_count from public.event_sources
union all
  select 'research_changes' as table_name, count(*)::bigint as row_count from public.research_changes
union all
  select 'sources' as table_name, count(*)::bigint as row_count from public.sources
union all
  select 'venues' as table_name, count(*)::bigint as row_count from public.venues
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;

