-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: krazy-comic-crimson-event-completion-2026-07-18
-- Generated at: 2026-07-18T23:44:55.786701+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Fresh Wizards/EventLink pull inspected for this event-completion tranche.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-9348';
-- Reason: Fresh Wizards/EventLink pull inspected for this event-completion tranche.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-6809';
-- Reason: Fresh Wizards/EventLink pull inspected for this event-completion tranche.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-18899';
-- Reason: Fresh WPN pull reconfirmed Sunday Commander at Krazy Nick's Games.
update public.event_series set venue_id = 'krazy-nick-s-games', last_verified = '2026-07-18' where id is not distinct from 'krazy-nick-s-games-krazy-commander-sundays-0-13-00';
-- Reason: Fresh WPN pull reconfirmed Wednesday Commander at Krazy Nick's Games.
update public.event_series set venue_id = 'krazy-nick-s-games', last_verified = '2026-07-18' where id is not distinct from 'krazy-nick-s-games-krazy-commander-wednesdays-3-16-00';
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('krazy-nick-s-games', 'Magic Presents: God of Mischief Krazy Commander', 'Commander', 'special', 'all', null, '13:00', '2026-07-19', null, 0.0, 'USD', 'Wizards/EventLink lists a Sunday, July 19, 2026 Magic Presents: God of Mischief Commander free-play event at Krazy Nick''s Games at 1:00 PM. Event copy says more information will be posted on store socials.', 'high', 'active', '2026-07-18', 'krazy-nicks-god-of-mischief-commander-2026-07-19');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9348', 'krazy-nicks-god-of-mischief-commander-2026-07-19', null, 'Wizards/EventLink dated Commander special evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('krazy-nick-s-games', 'Krazy Modern Thursdays', 'Modern', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":4,"startTime":"19:00"}'::jsonb, '19:00', '2026-07-23', null, 5.0, 'USD', 'Fresh Wizards/EventLink pull lists recurring Thursday 7:00 PM Modern at Krazy Nick''s Games with $5 entry and store-credit prizing based on attendance.', 'high', 'active', '2026-07-18', 'krazy-nicks-modern-thursdays-4-19-00');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9348', 'krazy-nicks-modern-thursdays-4-19-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('krazy-nick-s-games', 'Krazy Pauper Friday', 'Pauper', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"19:00"}'::jsonb, '19:00', '2026-07-24', null, 5.0, 'USD', 'Fresh Wizards/EventLink pull lists recurring Friday 7:00 PM Pauper at Krazy Nick''s Games with $5 entry and store-credit prizing.', 'high', 'active', '2026-07-18', 'krazy-nicks-pauper-friday-5-19-00');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9348', 'krazy-nicks-pauper-friday-5-19-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('krazy-nick-s-games', 'Krazy Standard Showdown', 'Standard', 'constructed', 'all', null, '19:00', '2026-07-24', null, 5.0, 'USD', 'Wizards/EventLink lists a Friday, July 24, 2026 7:00 PM Standard Showdown at Krazy Nick''s Games with $5 entry, promos for top players, and store-credit prizing.', 'high', 'active', '2026-07-18', 'krazy-nicks-standard-showdown-2026-07-24');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9348', 'krazy-nicks-standard-showdown-2026-07-24', null, 'Wizards/EventLink dated Standard Showdown evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('krazy-nick-s-games', 'Krazy Hobbit Prerelease', 'Sealed', 'prerelease', 'all', null, null, '2026-08-07', '2026-08-08', 45.0, 'USD', 'Wizards/EventLink lists three The Hobbit prerelease sealed occurrences at Krazy Nick''s Games on August 7-8, 2026. Event copy says signups will be handled through the store website/socials and prizing will be based on attendance.', 'high', 'active', '2026-07-18', 'krazy-nicks-hobbit-prerelease-2026');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-9348', 'krazy-nicks-hobbit-prerelease-2026', null, 'Wizards/EventLink finite prerelease evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('krazy-nicks-hobbit-prerelease-2026', '2026-08-07', '19:00', null, 'single_source', 'confirmed', 45.0, null, 'Wizards/EventLink event 10989853 confirms Krazy Hobbit Prerelease at Krazy Nick''s Games on 2026-08-07 at 19:00.', 'krazy-nicks-hobbit-prerelease-2026-08-07-19-00');
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('krazy-nicks-hobbit-prerelease-2026', '2026-08-08', '12:00', null, 'single_source', 'confirmed', 45.0, null, 'Wizards/EventLink event 10989974 confirms Krazy Hobbit Prerelease at Krazy Nick''s Games on 2026-08-08 at 12:00.', 'krazy-nicks-hobbit-prerelease-2026-08-08-12-00');
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('krazy-nicks-hobbit-prerelease-2026', '2026-08-08', '16:00', null, 'single_source', 'confirmed', 45.0, null, 'Wizards/EventLink event 10989985 confirms Krazy Hobbit Prerelease at Krazy Nick''s Games on 2026-08-08 at 16:00.', 'krazy-nicks-hobbit-prerelease-2026-08-08-16-00');
-- Reason: Fresh WPN pull reconfirmed Friday 6:00 PM FNM Commander at Comic Quest.
update public.event_series set venue_id = 'comic-quest', confidence = 'high', last_verified = '2026-07-18' where id is not distinct from 'comic-quest-friday-night-magic-fnm-commander-5-18-00';
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('comic-quest', 'FNM Standard Showdown - Marvel Superheroes', 'Standard', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"18:00"}'::jsonb, '18:00', '2026-07-24', '2026-07-31', 0.0, 'USD', 'Fresh Wizards/EventLink pull lists Comic Quest Friday 6:00 PM FNM Standard Showdown on July 24 and July 31, 2026. Event copy describes 1v1 Standard and weekly winner promo support.', 'high', 'active', '2026-07-18', 'comic-quest-fnm-standard-showdown-5-18-00');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6809', 'comic-quest-fnm-standard-showdown-5-18-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('comic-quest', 'Marvel Superheroes Commander Party #2', 'Commander', 'special', 'all', null, '18:00', '2026-07-31', null, 0.0, 'USD', 'Wizards/EventLink lists Marvel Superheroes Commander Party #2 at Comic Quest on Friday, July 31, 2026 at 6:00 PM. Event copy describes Commander Party goals/achievements using provided party cards.', 'high', 'active', '2026-07-18', 'comic-quest-marvel-commander-party-2026-07-31');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6809', 'comic-quest-marvel-commander-party-2026-07-31', null, 'Wizards/EventLink dated Commander Party evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('comic-quest', 'The Hobbit Prerelease', 'Sealed', 'prerelease', 'all', null, null, '2026-08-07', '2026-08-09', null, 'USD', 'Wizards/EventLink lists Comic Quest Hobbit prerelease sealed events on August 7, 8, and 9, 2026. Entry fee is TBA/zero in the WPN pull; do not infer free entry.', 'high', 'active', '2026-07-18', 'comic-quest-hobbit-prerelease-2026');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6809', 'comic-quest-hobbit-prerelease-2026', null, 'Wizards/EventLink finite prerelease evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('comic-quest-hobbit-prerelease-2026', '2026-08-07', '18:00', null, 'single_source', 'confirmed', null, null, 'Wizards/EventLink event 11253790 confirms The Hobbit prerelease at Comic Quest on 2026-08-07 at 18:00; Friday 2HG / Two-Headed Giant team play.', 'comic-quest-hobbit-prerelease-2026-08-07-18-00');
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('comic-quest-hobbit-prerelease-2026', '2026-08-08', '12:00', null, 'single_source', 'confirmed', null, null, 'Wizards/EventLink event 11253792 confirms The Hobbit prerelease at Comic Quest on 2026-08-08 at 12:00; Saturday 1v1 prerelease.', 'comic-quest-hobbit-prerelease-2026-08-08-12-00');
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('comic-quest-hobbit-prerelease-2026', '2026-08-09', '12:00', null, 'single_source', 'confirmed', null, null, 'Wizards/EventLink event 11253793 confirms The Hobbit prerelease at Comic Quest on 2026-08-09 at 12:00; Sunday 1v1 prerelease.', 'comic-quest-hobbit-prerelease-2026-08-09-12-00');
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('comic-quest', 'The Hobbit Commander Party', 'Commander', 'special', 'all', null, '18:00', '2026-08-21', '2026-09-18', 0.0, 'USD', 'Wizards/EventLink lists The Hobbit Commander Party events at Comic Quest on August 21 and September 18, 2026 at 6:00 PM.', 'high', 'active', '2026-07-18', 'comic-quest-hobbit-commander-party-2026');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6809', 'comic-quest-hobbit-commander-party-2026', null, 'Wizards/EventLink dated Commander Party evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('comic-quest-hobbit-commander-party-2026', '2026-08-21', '18:00', null, 'single_source', 'confirmed', 0.0, null, 'Wizards/EventLink event 11253783 confirms The Hobbit Commander Party at Comic Quest on 2026-08-21 at 18:00.', 'comic-quest-hobbit-commander-party-2026-08-21-18-00');
-- Reason: Capture separate WPN-confirmed occurrence time for finite event series.
insert into public.event_occurrences (series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details, id) values ('comic-quest-hobbit-commander-party-2026', '2026-09-18', '18:00', null, 'single_source', 'confirmed', 0.0, null, 'Wizards/EventLink event 11253785 confirms The Hobbit Commander Party at Comic Quest on 2026-09-18 at 18:00.', 'comic-quest-hobbit-commander-party-2026-09-18-18-00');
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('comic-quest', 'Magic Presents: Heart of the Mountain Commander Event', 'Commander', 'special', 'all', null, '18:00', '2026-09-04', null, 0.0, 'USD', 'Wizards/EventLink lists Magic Presents: Heart of the Mountain Commander Event at Comic Quest on Friday, September 4, 2026 at 6:00 PM.', 'high', 'active', '2026-07-18', 'comic-quest-heart-of-the-mountain-2026-09-04');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6809', 'comic-quest-heart-of-the-mountain-2026-09-04', null, 'Wizards/EventLink dated Commander special evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Fresh WPN pull reconfirmed Friday Commander Night at The Crimson Guild South El Monte.
update public.event_series set venue_id = 'the-crimson-guild-south-el-monte', last_verified = '2026-07-18' where id is not distinct from 'the-crimson-guild-south-el-monte-the-crimson-guild-commander-night-5-18-00';
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('the-crimson-guild-south-el-monte', 'The Crimson Guild Draft', 'Draft', 'draft', 'all', '{"frequency":"weekly","dayOfWeek":3,"startTime":"19:00"}'::jsonb, '19:00', '2026-07-22', null, 20.0, 'USD', 'Fresh Wizards/EventLink pull lists recurring Wednesday 7:00 PM draft at The Crimson Guild - South El Monte with $20 entry.', 'high', 'active', '2026-07-18', 'crimson-guild-draft-wednesday-3-19-00');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18899', 'crimson-guild-draft-wednesday-3-19-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('the-crimson-guild-south-el-monte', 'Friday Night Magic Pauper', 'Pauper', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"19:00"}'::jsonb, '19:00', '2026-07-24', null, 10.0, 'USD', 'Fresh Wizards/EventLink pull lists recurring Friday 7:00 PM FNM Pauper at The Crimson Guild - South El Monte with $10 entry. Event copy frames it as a chill commons-only FNM environment.', 'high', 'active', '2026-07-18', 'crimson-guild-fnm-pauper-5-19-00');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18899', 'crimson-guild-fnm-pauper-5-19-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('the-crimson-guild-south-el-monte', 'The Crimson Guild Standard Showdown', 'Standard', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":0,"startTime":"16:00"}'::jsonb, '16:00', '2026-07-19', null, 10.0, 'USD', 'Fresh Wizards/EventLink pull lists recurring Sunday 4:00 PM Standard Showdown at The Crimson Guild - South El Monte with $10 entry, entry pack, and prize pool support.', 'high', 'active', '2026-07-18', 'crimson-guild-standard-showdown-0-16-00');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18899', 'crimson-guild-standard-showdown-0-16-00', null, 'Wizards/EventLink evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Catalog source-supported current/future Magic event missing from Supabase.
insert into public.event_series (venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified, id) values ('the-crimson-guild-south-el-monte', 'Marvel Super Heroes Commander Party', 'Commander', 'special', 'all', null, '19:00', '2026-07-31', null, 0.0, 'USD', 'Wizards/EventLink contains two same-time Crimson Guild Marvel Super Heroes Commander Party listings for Friday, July 31, 2026 at 7:00 PM. Collapsed to one planning event; copy mentions Commander Party rules and promo/entry support while supplies last.', 'high', 'active', '2026-07-18', 'crimson-guild-marvel-commander-party-2026-07-31');
-- Reason: Attach WPN provenance to the proposed or refreshed event row.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-18899', 'crimson-guild-marvel-commander-party-2026-07-31', null, 'Wizards/EventLink dated Commander Party evidence') on conflict (source_id, series_id) where series_id is not null do nothing;
-- Reason: Create visible Updates marker for the proposed event-completion batch.
insert into public.research_changes (detected_at, change_type, entity_type, entity_id, summary, review_status, id) values ('2026-07-18T16:35:00-07:00', 'new_event', 'event', 'krazy-comic-crimson-event-completion', 'Proposed fresh Wizards/EventLink event-completion pass for Krazy Nick''s Games, Comic Quest, and The Crimson Guild, adding current Commander specials, prereleases, draft, Standard, Modern, and Pauper rows where source-supported.', 'proposed', 'chg-2026-07-18-krazy-comic-crimson-event-completion');

-- Post-write row-count verification:
select * from (
  select 'event_occurrences' as table_name, count(*)::bigint as row_count from public.event_occurrences
union all
  select 'event_series' as table_name, count(*)::bigint as row_count from public.event_series
union all
  select 'event_sources' as table_name, count(*)::bigint as row_count from public.event_sources
union all
  select 'research_changes' as table_name, count(*)::bigint as row_count from public.research_changes
union all
  select 'sources' as table_name, count(*)::bigint as row_count from public.sources
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;
