-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: nearby-high-value-completion-pass-2026-07-18
-- Generated at: 2026-07-18T17:02:34.965499+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Wizards/EventLink snapshot still supports Hobby Overflow Thursday casual Commander; no new event write is needed.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-17690';
-- Reason: Wizards/EventLink snapshot supports Requiem Monday Commander plus missing Wednesday Magic and Friday Night Magic rows.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-14480';
-- Reason: Requiem's official weekly-events page remains current and explicitly frames Magic tournaments as a normal weekly-event category while warning that collaborations can change the weekly schedule.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-requiem-weekly-events-2026-07-17';
-- Reason: Wizards/EventLink snapshot supports Spellhold's broad weekly Magic schedule plus August 2026 The Hobbit prerelease rows.
update public.sources set health_status = 'current', last_checked = '2026-07-18' where id is not distinct from 'src-wpn-6830';
-- Reason: Capture Spellhold's official site as Evidence for current operation, MTG inventory depth, store hours, and weekly/special event routing.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-spellhold-site-2026-07-18', 'Spellhold Games official website and weekly events route', 'https://www.spellholdgames.com/', 'officialWebsite', 'current', '2026-07-18');
-- Reason: Expose Spellhold's official site as visible Places Evidence.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'spellhold-games', 'src-spellhold-site-2026-07-18', 'official site / MTG inventory / weekly-event route support');
-- Reason: Capture a secondary review/directory surface that summarizes Spellhold's Google-derived rating, MTG specialty, tournaments, singles, and store services.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-spellhold-cardshows-2026-07-18', 'CardShows.io Spellhold Games review/directory profile', 'https://cardshows.io/shops/spellhold-games-orange', 'community', 'current', '2026-07-18');
-- Reason: Expose Spellhold's review/directory support on the Places Evidence tab.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'spellhold-games', 'src-spellhold-cardshows-2026-07-18', 'review/directory support for MTG focus, events, singles, and store prominence');
-- Reason: Capture a human-readable EventLink mirror corroborating Spellhold Saturday Commander on July 25, 2026 and routing back to Wizards/EventLink.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-spellhold-cardcommunity-commander-2026-07-18', 'CardCommunity mirror for Spellhold Saturday Open Play Commander', 'https://cardcommunity.org/event/dbad024b-9f0a-4dcf-a9ad-a5bb1cba008b?on=2026-07-25', 'eventsPage', 'current', '2026-07-18');
-- Reason: Expose the public EventLink mirror as supplemental Evidence without making it more canonical than Wizards/EventLink.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'spellhold-games', 'src-spellhold-cardcommunity-commander-2026-07-18', 'EventLink mirror / Commander cross-check');
-- Reason: Make a current store/Wizards-supported non-Commander Magic row visible while preserving format uncertainty.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('requiem-wednesday-magic', 'requiem-coffee-tea-and-fantasy', 'Magic at Requiem', 'Magic', 'casual', 'all', '{"frequency":"weekly","dayOfWeek":3,"startTime":"18:00"}'::jsonb, '18:00', '2026-07-22', null, 0.0, 'USD', 'Wizards/EventLink lists weekly Wednesday Magic at Requiem at 6:00 PM. The description says Magic the Gathering at Requiem Cafe is casual and fun for everyone; exact format is unspecified.', 'medium', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to Requiem Wednesday Magic.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-14480', 'requiem-wednesday-magic', null, 'Wizards/EventLink recurring general Magic evidence');
-- Reason: Make Requiem's current FNM/Magic signal visible while preserving format uncertainty.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('requiem-friday-night-magic', 'requiem-coffee-tea-and-fantasy', 'Friday Night Magic at Requiem', 'Magic', 'special', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"18:00"}'::jsonb, '18:00', '2026-07-24', null, 0.0, 'USD', 'Wizards/EventLink lists weekly Friday Night Magic at Requiem at 6:00 PM. The description says Friday Night Magic at Requiem Cafe is casual and fun for everyone; exact format is unspecified.', 'medium', 'active', '2026-07-18');
-- Reason: Attach WPN provenance to Requiem FNM.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-14480', 'requiem-friday-night-magic', null, 'Wizards/EventLink recurring FNM evidence');
-- Reason: Catalog current non-Commander Magic format coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-monday-modern', 'spellhold-games', 'Monday Modern', 'Modern', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":1,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-20', null, 5.0, 'USD', 'Wizards/EventLink lists weekly Monday Modern at Spellhold Games at 7:30 PM with $5 entry and store-credit prizing.', 'high', 'active', '2026-07-18');
-- Reason: Catalog current non-Commander Magic format coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-tuesday-legacy', 'spellhold-games', 'Tuesday Legacy', 'Legacy', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":2,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-21', null, 5.0, 'USD', 'Wizards/EventLink lists weekly Tuesday Legacy at Spellhold Games at 7:30 PM with $5 entry and store-credit prizing.', 'high', 'active', '2026-07-18');
-- Reason: Catalog current Standard Showdown coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-wednesday-standard-showdown', 'spellhold-games', 'Wednesday Standard Showdown', 'Standard', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":3,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-22', null, 5.0, 'USD', 'Wizards/EventLink lists weekly Wednesday Standard Showdown at Spellhold Games at 7:30 PM with $5 entry and store-credit prizing.', 'high', 'active', '2026-07-18');
-- Reason: Catalog current non-Commander Magic format coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-thursday-pioneer', 'spellhold-games', 'Thursday Pioneer', 'Pioneer', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":4,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-23', null, 5.0, 'USD', 'Wizards/EventLink lists weekly Thursday Pioneer at Spellhold Games at 7:30 PM with $5 entry and store-credit prizing.', 'high', 'active', '2026-07-18');
-- Reason: Catalog current FNM draft coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-friday-night-magic-draft', 'spellhold-games', 'Friday Night Magic Draft', 'Draft', 'draft', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"19:00"}'::jsonb, '19:00', '2026-07-24', null, 25.0, 'USD', 'Wizards/EventLink lists weekly Friday Night Magic Draft at Spellhold Games at 7:00 PM with $25 entry and booster-pack prizing.', 'high', 'active', '2026-07-18');
-- Reason: Catalog current non-Commander Magic format coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-premodern-friday', 'spellhold-games', 'Premodern Friday', 'Premodern', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":5,"startTime":"19:30"}'::jsonb, '19:30', '2026-07-24', null, 5.0, 'USD', 'Wizards/EventLink lists weekly Premodern Friday at Spellhold Games at 7:30 PM with $5 entry and store-credit prizing.', 'high', 'active', '2026-07-18');
-- Reason: Catalog current non-Commander Magic format coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-sunday-pauper', 'spellhold-games', 'Sunday Pauper', 'Pauper', 'constructed', 'all', '{"frequency":"weekly","dayOfWeek":0,"startTime":"16:30"}'::jsonb, '16:30', '2026-07-19', null, 5.0, 'USD', 'Wizards/EventLink lists weekly Sunday Pauper at Spellhold Games at 4:30 PM with $5 entry and store-credit prizing.', 'high', 'active', '2026-07-18');
-- Reason: Catalog upcoming prerelease/sealed coverage missing from the app.
insert into public.event_series (id, venue_id, title, format, event_type, bracket, recurrence, default_start_time, start_date, end_date, entry_fee, currency, details, confidence, event_status, last_verified) values ('spellhold-hobbit-prerelease-2026', 'spellhold-games', 'The Hobbit Prerelease', 'Sealed', 'prerelease', 'all', 'null'::jsonb, null, '2026-08-07', '2026-08-09', 50.0, 'USD', 'Wizards/EventLink lists five The Hobbit prerelease sealed occurrences at Spellhold Games from August 7-9, 2026. Event copy says $50 entry and booster-pack prizing.', 'high', 'active', '2026-07-18');
-- Reason: Attach WPN evidence to Spellhold Monday Modern.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-monday-modern', null, 'Wizards/EventLink recurring Modern evidence');
-- Reason: Attach WPN evidence to Spellhold Tuesday Legacy.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-tuesday-legacy', null, 'Wizards/EventLink recurring Legacy evidence');
-- Reason: Attach WPN evidence to Spellhold Standard Showdown.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-wednesday-standard-showdown', null, 'Wizards/EventLink recurring Standard Showdown evidence');
-- Reason: Attach WPN evidence to Spellhold Thursday Pioneer.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-thursday-pioneer', null, 'Wizards/EventLink recurring Pioneer evidence');
-- Reason: Attach WPN evidence to Spellhold FNM Draft.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-friday-night-magic-draft', null, 'Wizards/EventLink recurring FNM Draft evidence');
-- Reason: Attach WPN evidence to Spellhold Premodern Friday.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-premodern-friday', null, 'Wizards/EventLink recurring Premodern evidence');
-- Reason: Attach WPN evidence to Spellhold Sunday Pauper.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-sunday-pauper', null, 'Wizards/EventLink recurring Pauper evidence');
-- Reason: Attach WPN evidence to Spellhold Hobbit prerelease.
insert into public.event_sources (source_id, series_id, occurrence_id, relationship) values ('src-wpn-6830', 'spellhold-hobbit-prerelease-2026', null, 'Wizards/EventLink dated prerelease evidence');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('spellhold-hobbit-prerelease-2026-08-07-19-00', 'spellhold-hobbit-prerelease-2026', '2026-08-07', '19:00', null, 'single_source', 'confirmed', 50.0, null, 'Wizards/EventLink confirms The Hobbit Prerelease at Spellhold Games on Friday, August 7, 2026 at 7:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('spellhold-hobbit-prerelease-2026-08-08-12-00', 'spellhold-hobbit-prerelease-2026', '2026-08-08', '12:00', null, 'single_source', 'confirmed', 50.0, null, 'Wizards/EventLink confirms The Hobbit Prerelease at Spellhold Games on Saturday, August 8, 2026 at 12:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('spellhold-hobbit-prerelease-2026-08-08-16-00', 'spellhold-hobbit-prerelease-2026', '2026-08-08', '16:00', null, 'single_source', 'confirmed', 50.0, null, 'Wizards/EventLink confirms The Hobbit Prerelease at Spellhold Games on Saturday, August 8, 2026 at 4:00 PM.');
-- Reason: Add exact dated prerelease occurrence.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('spellhold-hobbit-prerelease-2026-08-09-12-00', 'spellhold-hobbit-prerelease-2026', '2026-08-09', '12:00', null, 'single_source', 'confirmed', 50.0, null, 'Wizards/EventLink confirms The Hobbit Prerelease at Spellhold Games on Sunday, August 9, 2026 at 12:00 PM.');
-- Reason: Add exact dated prerelease occurrence while preserving the source-copy caveat.
insert into public.event_occurrences (id, series_id, occurrence_date, start_time, end_time, evidence_state, occurrence_status, entry_fee, capacity, details) values ('spellhold-hobbit-prerelease-2026-08-09-16-00', 'spellhold-hobbit-prerelease-2026', '2026-08-09', '16:00', null, 'single_source', 'confirmed', 50.0, null, 'Wizards/EventLink confirms The Hobbit Prerelease at Spellhold Games on Sunday, August 9, 2026 at 4:00 PM. Source description appears to repeat ''Saturday 4pm'' copy, but the scheduled date/time and title are Sunday 4pm.');
-- Reason: Recalibrate Spellhold's Places assessment after correcting incomplete Commander-only event coverage.
update public.venues set last_verified = '2026-07-18', assessment_notes = 'Spellhold has a broader and more reliable Magic calendar than the old Places note implied. Wizards/EventLink shows Saturday Commander plus weekly Modern, Legacy, Standard Showdown, Pioneer, FNM Draft, Premodern, Sunday Pauper, and The Hobbit prerelease dates; the official site supports current operation, MTG inventory depth, and weekly/special event routing. This improves Magic-overall activity and schedule reliability, but the store still reads as a broad/competitive Magic hub more than a proven solo-arrival Commander community. Proxy policy, bracket texture, pod formation, and Discord usefulness remain the main open questions.', assessment = '{"commanderActivity":3,"homeGroupPotential":3,"communityContinuity":3,"meetupAccessibility":3,"physicalEnvironment":4,"scheduleReliability":5,"newPlayerIntegration":3}'::jsonb where id is not distinct from 'spellhold-games';
-- Reason: Expose the corrected Spellhold fit/confidence reasoning on the Places page.
insert into public.evaluations (entity_type, entity_id, research_status, candidate_status, fit_grade, fit_score, confidence, positives, cautions, open_questions) values ('venue', 'spellhold-games', 'reviewed', 'neutral', 'B-', 3.6, 'medium-high', array['Wizards/EventLink shows a broad current weekly Magic schedule across Commander, Modern, Legacy, Standard, Pioneer, Draft, Premodern, and Pauper.', 'Official site supports active operation, MTG inventory depth, online singles/sealed catalog, and weekly/special-event routing.', 'Review/directory surfaces point to substantial MTG play space, singles, tournaments, and generally positive staff/community signals.']::text[], array['Best evidence points to broad/competitive Magic infrastructure, not necessarily a relaxed Commander-first solo-arrival environment.', 'Pricing/markup complaints appear in some review-derived surfaces, mainly around other TCG events, so event-pricing expectations should be checked.', 'Discord/public community evidence remains more flyer-board than proven LFG/community-texture support.']::text[], array['How welcoming is Saturday Commander for solo arrivals?', 'What are the actual proxy/bracket expectations for Commander?', 'Does the Discord contain useful LFG or event-reliability discussion beyond posted flyers?']::text[]) on conflict (entity_type, entity_id) do update set research_status = excluded.research_status, candidate_status = excluded.candidate_status, fit_grade = excluded.fit_grade, fit_score = excluded.fit_score, confidence = excluded.confidence, positives = excluded.positives, cautions = excluded.cautions, open_questions = excluded.open_questions;
-- Reason: Create a durable update marker before any live write.
insert into public.research_changes (id, detected_at, change_type, entity_type, entity_id, summary, review_status) values ('nearby-high-value-completion-pass-2026-07-18', '2026-07-18T09:00:00-07:00', 'event_update', 'venue', 'spellhold-games', 'Proposed nearby completion pass for Hobby Overflow, Requiem, and Spellhold. Hobby Overflow needs no new rows; Requiem gets missing Wednesday Magic and FNM rows; Spellhold gets broad weekly Magic format coverage and The Hobbit prerelease dates, with a Places assessment recalibration.', 'proposed');

-- Post-write row-count verification:
select * from (
  select 'entity_sources' as table_name, count(*)::bigint as row_count from public.entity_sources
union all
  select 'evaluations' as table_name, count(*)::bigint as row_count from public.evaluations
union all
  select 'event_occurrences' as table_name, count(*)::bigint as row_count from public.event_occurrences
union all
  select 'event_series' as table_name, count(*)::bigint as row_count from public.event_series
union all
  select 'event_sources' as table_name, count(*)::bigint as row_count from public.event_sources
union all
  select 'research_changes' as table_name, count(*)::bigint as row_count from public.research_changes
union all
  select 'sources' as table_name, count(*)::bigint as row_count from public.sources
union all
  select 'venues' as table_name, count(*)::bigint as row_count from public.venues
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;
