-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: packet-source-evidence-backfill-2026-07-17
-- Generated at: 2026-07-18T05:33:28.210420+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Capture the packet-derived Google-review mirror signal used to understand Tilted's active TCG/store-quality picture.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-tilted-keepup-2026-07-17', 'KeepUp review mirror for Tilted Gaming', 'https://www.keepupcards.com/shop/tilted-gaming-cerritos-ca', 'community', 'current', '2026-07-17');
-- Reason: Capture accessible Yelp-derived review/status texture for Tilted, including friendly atmosphere and TCG/Magic support signals.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-tilted-mapquest-2026-07-17', 'MapQuest / Yelp-derived listing for Tilted Gaming', 'https://www.mapquest.com/us/california/tilted-gaming-777729997', 'community', 'current', '2026-07-17');
-- Reason: Capture the direct mainstream review source for Buddies rather than relying only on secondary review mirrors.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-buddies-yelp-2026-07-17', 'Yelp page for Buddies Collectibles', 'https://www.yelp.com/biz/buddies-collectibles-gardena', 'community', 'current', '2026-07-17');
-- Reason: Capture local-journalism evidence supporting BYO's third-place/community-lounge read and financial/status caution.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-byo-laist-boyle-heights-beat-2026-07-17', 'LAist / Boyle Heights Beat profile of B.Y.O.GAMES', 'https://laist.com/news/los-angeles-activities/bring-your-own-games-byo-games-east-la-los-angeles', 'community', 'current', '2026-07-17');
-- Reason: Make Tilted's packet-derived review signal visible on the Places Evidence tab.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'tilted-gaming', 'src-tilted-keepup-2026-07-17', 'Google-derived review/store-quality signal');
-- Reason: Make Tilted's accessible Yelp-derived review/status support visible on the Places Evidence tab.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'tilted-gaming', 'src-tilted-mapquest-2026-07-17', 'Yelp-derived review/status signal');
-- Reason: Attach the direct Yelp page as first-class evidence for Buddies' store-quality, comfort, and review-texture read.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'buddies-collectibles', 'src-buddies-yelp-2026-07-17', 'direct Yelp review/fit signal');
-- Reason: Attach the local-journalism source that supports BYO's community-lounge assessment and status caution.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'b-y-o-games-llc', 'src-byo-laist-boyle-heights-beat-2026-07-17', 'local journalism/community and status signal');
-- Reason: Record the process correction and make the evidence-backfill proposal visible in Updates after approval.
insert into public.research_changes (id, detected_at, change_type, entity_type, entity_id, summary, review_status) values ('packet-source-evidence-backfill-2026-07-17', '2026-07-17T21:20:00-07:00', 'source_update', 'venue', 'buddies-collectibles', 'Packet-source disposition audit identified source signals that influenced Places reasoning but were not visible as Evidence; proposed backfill adds Tilted review mirrors, Buddies direct Yelp, and BYO local journalism. No event records changed.', 'proposed');

-- Post-write row-count verification:
select * from (
  select 'entity_sources' as table_name, count(*)::bigint as row_count from public.entity_sources
union all
  select 'research_changes' as table_name, count(*)::bigint as row_count from public.research_changes
union all
  select 'sources' as table_name, count(*)::bigint as row_count from public.sources
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;
