-- Generated by scripts/supabase_research_workflow.py. Review before applying.
-- Proposal: venue-hours-seed-2026-07-18
-- Generated at: 2026-07-19T03:27:50.636815+00:00
-- Before applying to live Supabase, create a deterministic export/backup.
begin;
set constraints all immediate;
-- Reason: Card Shop Hub provides a current-looking Magic and Monsters hours listing that agrees with another secondary directory; capture it as visible Evidence rather than hiding it in notes.
insert into public.sources (id, label, url, source_type, health_status, last_checked) values ('src-magicandmonsters-card-shop-hub-hours-2026-07-18', 'Card Shop Hub listing for Magic and Monsters hours', 'https://cardshophub.com/stores/magic-and-monsters', 'directory', 'current', '2026-07-18');
-- Reason: Make the hours source reachable from the Magic and Monsters Evidence tab.
insert into public.entity_sources (entity_type, entity_id, source_id, relationship) values ('venue', 'magic-and-monsters', 'src-magicandmonsters-card-shop-hub-hours-2026-07-18', 'secondary directory hours source; useful for planning but check before relying');
-- Reason: Seed partial official hours for a favorite/high-value venue while preserving that the full routine schedule is not yet captured.
insert into public.venue_hours (venue_id, status, weekly_hours, temporary_updates, source_id, last_verified, notes) values ('collectors-lounge-cypress', 'variable', '{"6":[{"open":"12:00","close":"22:00"}]}'::jsonb, '[]'::jsonb, 'src-collectorslounge-site-2026-07-14', '2026-07-18', 'Official site exposed only an ''Open today'' hours block at check time; Saturday 12 PM-10 PM is captured as a partial planning aid, with full weekly hours still needing confirmation.');
-- Reason: Seed official weekly hours for a frequently surfaced event venue.
insert into public.venue_hours (venue_id, status, weekly_hours, temporary_updates, source_id, last_verified, notes) values ('coretcg', 'verified', '{"0":[{"open":"11:00","close":"20:00"}],"1":[{"open":"11:00","close":"20:00"}],"2":[{"open":"11:00","close":"20:00"}],"3":[{"open":"11:00","close":"20:00"}],"4":[{"open":"11:00","close":"20:00"}],"5":[{"open":"11:00","close":"20:00"}],"6":[{"open":"11:00","close":"20:00"}]}'::jsonb, '[]'::jsonb, 'src-coretcg-official-site-2026-07-17', '2026-07-18', 'Official FAQ lists Monday-Sunday 11 AM-8 PM.');
-- Reason: Seed official weekly hours for a high-priority local venue.
insert into public.venue_hours (venue_id, status, weekly_hours, temporary_updates, source_id, last_verified, notes) values ('finch-sparrow', 'verified', '{"0":[{"open":"12:00","close":"22:00"}],"1":[{"open":"12:00","close":"22:00"}],"2":[{"open":"12:00","close":"22:00"}],"3":[{"open":"12:00","close":"22:00"}],"4":[{"open":"12:00","close":"22:00"}],"5":[{"open":"12:00","close":"22:00"}],"6":[{"open":"12:00","close":"22:00"}]}'::jsonb, '[]'::jsonb, 'src-finch-homepage-2026-07-14', '2026-07-18', 'Official site lists open 7 days a week, 12 PM-10 PM PST.');
-- Reason: Seed useful planning hours for a recently improved nearby candidate, while marking the source as directory-derived rather than official.
insert into public.venue_hours (venue_id, status, weekly_hours, temporary_updates, source_id, last_verified, notes) values ('jjs-collectibles', 'variable', '{"0":[{"open":"12:00","close":"21:00"}],"1":[{"open":"12:00","close":"22:00"}],"2":[{"open":"12:00","close":"22:00"}],"3":[{"open":"12:00","close":"22:00"}],"4":[{"open":"12:00","close":"22:00"}],"5":[{"open":"12:00","close":"22:00"}],"6":[{"open":"12:00","close":"22:00"}]}'::jsonb, '[]'::jsonb, 'src-jjs-keepup-reviews-2026-07-18', '2026-07-18', 'KeepUp directory lists Monday-Saturday 12 PM-10 PM and Sunday 12 PM-9 PM; treat as directory-derived and check before relying for a special trip.');
-- Reason: Seed current-looking secondary hours for a venue whose official site did not expose a clear weekly hours block during this pass.
insert into public.venue_hours (venue_id, status, weekly_hours, temporary_updates, source_id, last_verified, notes) values ('magic-and-monsters', 'variable', '{"0":[{"open":"11:00","close":"18:00"}],"1":[{"open":"11:00","close":"22:00"}],"2":[{"open":"11:00","close":"22:00"}],"3":[{"open":"11:00","close":"22:00"}],"4":[{"open":"11:00","close":"22:00"}],"5":[{"open":"11:00","close":"22:00"}],"6":[{"open":"11:00","close":"22:00"}]}'::jsonb, '[]'::jsonb, 'src-magicandmonsters-card-shop-hub-hours-2026-07-18', '2026-07-18', 'Card Shop Hub and Loc8NearMe agree on Monday-Saturday 11 AM-10 PM and Sunday 11 AM-6 PM; conflicting directory hours exist, so treat as useful but check before relying.');

-- Post-write row-count verification:
select * from (
  select 'entity_sources' as table_name, count(*)::bigint as row_count from public.entity_sources
union all
  select 'sources' as table_name, count(*)::bigint as row_count from public.sources
union all
  select 'venue_hours' as table_name, count(*)::bigint as row_count from public.venue_hours
) counts order by table_name;

-- Post-write duplicate occurrence check:
select series_id, occurrence_date, start_time, count(*)
from public.event_occurrences
group by series_id, occurrence_date, start_time
having count(*) > 1;
commit;
