"""Generate a deterministic Supabase seed from the current canonical snapshot.

This script reads UTF-8 JSON directly and writes UTF-8 SQL. It does not contact
Supabase and it never requires a service-role key.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "supabase" / "seed" / "0001_current_snapshot.sql"

COMMUNITIES = [
    {
        "id": "legendary-creature-club",
        "name": "Legendary Creature Club",
        "region": "Long Beach · South Bay",
        "research_status": "reviewed",
        "formats": ["Commander", "Meetups"],
        "primary_channel": "Discord",
        "summary": (
            "A geographically relevant player group with a Long Beach and South "
            "Bay center of gravity. Its proximity makes it especially interesting "
            "for repeat local relationships."
        ),
        "signal": "Closer regional fit",
        "next_question": (
            "Normalize its current meetup cadence, venue relationships, and "
            "newcomer coordination pattern."
        ),
    },
    {
        "id": "infinite-loop-mtg",
        "name": "Infinite Loop MTG",
        "region": "Los Angeles · northern coverage",
        "research_status": "reviewed",
        "formats": ["Magic", "Commander"],
        "primary_channel": "Discord",
        "summary": (
            "A strong regional Magic community lead whose events tend to be "
            "farther north. Still appealing when the event or group signal is "
            "unusually strong."
        ),
        "signal": "High interest, farther travel",
        "next_question": (
            "Map recurring hosts and separate nearby opportunities from the "
            "broader LA stream."
        ),
    },
    {
        "id": "mtg-oc",
        "name": "MTG OC / ProjectCCG",
        "region": "Orange County",
        "research_status": "discovery",
        "formats": ["Magic", "Community"],
        "primary_channel": "Discord",
        "summary": (
            "An Orange County community surface selected for Magic and local "
            "coverage. It may provide useful cross-store discovery and player "
            "coordination."
        ),
        "signal": "Regional discovery lead",
        "next_question": (
            "Clarify whether the useful unit is one community, several channels, "
            "or organizer-linked venue activity."
        ),
    },
]


def read_json(name: str) -> list[dict[str, Any]]:
    return json.loads((ROOT / name).read_text(encoding="utf-8"))


def sql(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def jsonb(value: Any) -> str:
    encoded = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return f"{sql(encoded)}::jsonb"


def text_array(values: list[str] | None) -> str:
    return "array[" + ", ".join(sql(value) for value in (values or [])) + "]::text[]"


def insert_values(
    table: str,
    columns: list[str],
    rows: list[list[str]],
    conflict: str,
) -> str:
    if not rows:
        return ""
    rendered_rows = ",\n".join("  (" + ", ".join(row) + ")" for row in rows)
    return (
        f"insert into public.{table} ({', '.join(columns)}) values\n"
        f"{rendered_rows}\n"
        f"on conflict {conflict};\n"
    )


def normalized_research_status(store: dict[str, Any]) -> str:
    evaluation = store.get("evaluation") or {}
    raw = evaluation.get("researchStatus") or store.get("researchStatus")
    return {
        "wizards-discovery": "discovery",
        "partial": "reviewed",
        "reviewed": "reviewed",
        "deepened": "deepened",
        "discovery": "discovery",
    }.get(raw, "discovery")


def main() -> None:
    stores = read_json("stores.json")
    events = read_json("events.json")
    sources = read_json("sources.json")
    changes = read_json("changes.json")

    snapshot_at = max(change["detectedAt"] for change in changes)
    sections: list[str] = [
        "-- Generated by scripts/generate_supabase_seed.py. Do not hand-edit.",
        "-- Source files: stores.json, events.json, sources.json, changes.json.",
        "begin;",
        (
            "insert into public.dataset_metadata "
            "(id, schema_version, snapshot_at, description) values "
            f"('primary', 1, {sql(snapshot_at)}, "
            "'Verified import of the current file-backed research snapshot.') "
            "on conflict (id) do update set "
            "schema_version = excluded.schema_version, "
            "snapshot_at = excluded.snapshot_at, "
            "description = excluded.description;"
        ),
    ]

    sections.append(
        insert_values(
            "venues",
            [
                "id", "name", "city", "address", "phone", "website",
                "events_url", "instagram", "wpn_premium", "distance_miles",
                "operating_status", "research_status", "last_verified",
                "assessment_notes", "assessment",
            ],
            [
                [
                    sql(store["id"]),
                    sql(store["name"]),
                    sql(store.get("city")),
                    sql(store.get("address")),
                    sql(store.get("phone")),
                    sql(store.get("website")),
                    sql(store.get("eventsUrl")),
                    sql(store.get("instagram")),
                    sql(bool(store.get("wpnPremium"))),
                    sql(store.get("distanceMiles")),
                    sql(store.get("status") or "unknown"),
                    sql(normalized_research_status(store)),
                    sql(store.get("lastVerified")),
                    sql(store.get("assessmentNotes")),
                    jsonb(store.get("assessment") or {}),
                ]
                for store in stores
            ],
            (
                "(id) do update set name = excluded.name, city = excluded.city, "
                "address = excluded.address, phone = excluded.phone, "
                "website = excluded.website, events_url = excluded.events_url, "
                "instagram = excluded.instagram, wpn_premium = excluded.wpn_premium, "
                "distance_miles = excluded.distance_miles, "
                "operating_status = excluded.operating_status, "
                "research_status = excluded.research_status, "
                "last_verified = excluded.last_verified, "
                "assessment_notes = excluded.assessment_notes, "
                "assessment = excluded.assessment"
            ),
        )
    )

    sections.append(
        insert_values(
            "communities",
            [
                "id", "name", "region", "research_status", "formats",
                "primary_channel", "summary", "signal", "next_question",
            ],
            [
                [
                    sql(item["id"]),
                    sql(item["name"]),
                    sql(item["region"]),
                    sql(item["research_status"]),
                    text_array(item["formats"]),
                    sql(item["primary_channel"]),
                    sql(item["summary"]),
                    sql(item["signal"]),
                    sql(item["next_question"]),
                ]
                for item in COMMUNITIES
            ],
            (
                "(id) do update set name = excluded.name, region = excluded.region, "
                "research_status = excluded.research_status, "
                "formats = excluded.formats, primary_channel = excluded.primary_channel, "
                "summary = excluded.summary, signal = excluded.signal, "
                "next_question = excluded.next_question"
            ),
        )
    )

    sections.append(
        insert_values(
            "sources",
            ["id", "label", "url", "source_type", "health_status", "last_checked"],
            [
                [
                    sql(source["id"]),
                    sql(source["label"]),
                    sql(source.get("url")),
                    sql(source.get("type") or "unknown"),
                    "'unknown'",
                    sql(source.get("lastChecked")),
                ]
                for source in sources
            ],
            (
                "(id) do update set label = excluded.label, url = excluded.url, "
                "source_type = excluded.source_type, "
                "health_status = excluded.health_status, "
                "last_checked = excluded.last_checked"
            ),
        )
    )

    entity_source_rows = []
    for store in stores:
        for source_id in store.get("sourceIds") or []:
            entity_source_rows.append(
                ["'venue'", sql(store["id"]), sql(source_id), "'evidence'"]
            )
    sections.append(
        insert_values(
            "entity_sources",
            ["entity_type", "entity_id", "source_id", "relationship"],
            entity_source_rows,
            "(entity_type, entity_id, source_id) do nothing",
        )
    )

    series_rows = []
    occurrence_rows = []
    event_source_rows = []
    for event in events:
        recurrence = event.get("recurrence")
        start_time = (
            (recurrence or {}).get("startTime")
            if recurrence
            else event.get("startTime")
        )
        series_rows.append(
            [
                sql(event["id"]),
                sql(event["storeId"]),
                "null",
                sql(event["title"]),
                sql(event.get("format")),
                sql(event.get("eventType")),
                sql(event.get("bracket")),
                jsonb(recurrence) if recurrence else "null",
                sql(start_time),
                sql(event.get("startDate")),
                sql(event.get("endDate")),
                sql(event.get("entryFee")),
                sql(event.get("currency") or "USD"),
                sql(event.get("details")),
                sql(event.get("confidence") or "low"),
                sql(event.get("status") or "unknown"),
                sql(event.get("lastVerified")),
            ]
        )
        if recurrence:
            event_source_rows.append(
                [sql(event["sourceId"]), sql(event["id"]), "null", "'evidence'"]
            )
        else:
            occurrence_id = event["id"] + "--occurrence"
            occurrence_rows.append(
                [
                    sql(occurrence_id),
                    sql(event["id"]),
                    sql(event["startDate"]),
                    sql(event.get("startTime")),
                    "null",
                    "'single_source'",
                    "'confirmed'",
                    sql(event.get("entryFee")),
                    "null",
                    sql(event.get("details")),
                ]
            )
            event_source_rows.append(
                [sql(event["sourceId"]), "null", sql(occurrence_id), "'evidence'"]
            )

    sections.append(
        insert_values(
            "event_series",
            [
                "id", "venue_id", "community_id", "title", "format",
                "event_type", "bracket", "recurrence", "default_start_time",
                "start_date", "end_date", "entry_fee", "currency", "details",
                "confidence", "event_status", "last_verified",
            ],
            series_rows,
            (
                "(id) do update set venue_id = excluded.venue_id, "
                "community_id = excluded.community_id, title = excluded.title, "
                "format = excluded.format, event_type = excluded.event_type, "
                "bracket = excluded.bracket, recurrence = excluded.recurrence, "
                "default_start_time = excluded.default_start_time, "
                "start_date = excluded.start_date, end_date = excluded.end_date, "
                "entry_fee = excluded.entry_fee, currency = excluded.currency, "
                "details = excluded.details, confidence = excluded.confidence, "
                "event_status = excluded.event_status, "
                "last_verified = excluded.last_verified"
            ),
        )
    )
    sections.append(
        insert_values(
            "event_occurrences",
            [
                "id", "series_id", "occurrence_date", "start_time", "end_time",
                "evidence_state", "occurrence_status", "entry_fee", "capacity",
                "details",
            ],
            occurrence_rows,
            (
                "(id) do update set series_id = excluded.series_id, "
                "occurrence_date = excluded.occurrence_date, "
                "start_time = excluded.start_time, end_time = excluded.end_time, "
                "evidence_state = excluded.evidence_state, "
                "occurrence_status = excluded.occurrence_status, "
                "entry_fee = excluded.entry_fee, capacity = excluded.capacity, "
                "details = excluded.details"
            ),
        )
    )
    sections.append(
        insert_values(
            "event_sources",
            ["source_id", "series_id", "occurrence_id", "relationship"],
            event_source_rows,
            "do nothing",
        )
    )

    evaluation_rows = []
    for store in stores:
        evaluation = store.get("evaluation")
        if not evaluation:
            continue
        evaluation_rows.append(
            [
                "'venue'",
                sql(store["id"]),
                sql(normalized_research_status(store)),
                sql(evaluation.get("candidateStatus")),
                sql(evaluation.get("fitGrade")),
                sql(evaluation.get("fitScore")),
                sql(evaluation.get("confidence") or "low"),
                text_array(evaluation.get("positives")),
                text_array(evaluation.get("cautions")),
                text_array(evaluation.get("openQuestions")),
            ]
        )
    sections.append(
        insert_values(
            "evaluations",
            [
                "entity_type", "entity_id", "research_status",
                "candidate_status", "fit_grade", "fit_score", "confidence",
                "positives", "cautions", "open_questions",
            ],
            evaluation_rows,
            (
                "(entity_type, entity_id) do update set "
                "research_status = excluded.research_status, "
                "candidate_status = excluded.candidate_status, "
                "fit_grade = excluded.fit_grade, fit_score = excluded.fit_score, "
                "confidence = excluded.confidence, positives = excluded.positives, "
                "cautions = excluded.cautions, "
                "open_questions = excluded.open_questions"
            ),
        )
    )

    sections.append(
        insert_values(
            "research_changes",
            [
                "id", "detected_at", "change_type", "entity_type", "entity_id",
                "summary", "review_status",
            ],
            [
                [
                    sql(change["id"]),
                    sql(change["detectedAt"]),
                    sql(change["changeType"]),
                    sql(change["entityType"]),
                    sql(change["entityId"]),
                    sql(change["summary"]),
                    sql(change["reviewStatus"]),
                ]
                for change in changes
            ],
            (
                "(id) do update set detected_at = excluded.detected_at, "
                "change_type = excluded.change_type, "
                "entity_type = excluded.entity_type, entity_id = excluded.entity_id, "
                "summary = excluded.summary, review_status = excluded.review_status"
            ),
        )
    )

    sections.extend(
        [
            "commit;",
            "",
            "-- Acceptance counts for this snapshot:",
            "select 'venues' as table_name, count(*) as row_count from public.venues",
            "union all select 'communities', count(*) from public.communities",
            "union all select 'sources', count(*) from public.sources",
            "union all select 'event_series', count(*) from public.event_series",
            "union all select 'event_occurrences', count(*) from public.event_occurrences",
            "union all select 'research_changes', count(*) from public.research_changes",
            "order by table_name;",
        ]
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n\n".join(section for section in sections if section), encoding="utf-8")
    print(
        "Generated "
        f"{OUTPUT.relative_to(ROOT)}: "
        f"{len(stores)} venues, {len(COMMUNITIES)} communities, "
        f"{len(sources)} sources, {len(events)} series, "
        f"{len(occurrence_rows)} dated occurrences, {len(changes)} changes."
    )


if __name__ == "__main__":
    main()
