-- Expand the Discord monitoring map with the accepted Discord/community pass 2
-- routes. This is monitoring memory only: no automation, browser writes, or
-- survey-history tables are added.

insert into public.discord_access_profiles (
  source_id,
  server_id,
  server_name,
  access_state,
  content_access,
  role_gate,
  preferred_access_surface,
  user_action_required,
  known_internal_target,
  last_successful_access_method,
  automation_suitability,
  route_value,
  monitoring_cadence,
  monitoring_reason,
  last_checked,
  last_useful_signal_at,
  notes
) values
  (
    'src-collectors-discord-2026-07-14',
    null,
    'Collectors Lounge - Cypress Discord',
    'joined',
    'accessible',
    'present',
    'in_app_browser',
    false,
    '#mtg-announcements-and-events, #q-and-a, #event-rules',
    'Existing signed-in in-app browser Discord session',
    'manual_session',
    'high',
    'weekly',
    'High-value route for current weekly schedule images, signup codes, casual/optimized Commander separation, same-day coordination, and rules/policy checks.',
    '2026-07-20',
    '2026-07-19',
    'Accepted pass 2 found a current weekly Magic schedule image and same-day draft coordination. Direct server/channel IDs were not preserved in the run note and should be recovered on the next map-driven check.'
  ),
  (
    'src-hobbyoverflow-discord-invite-2026-07-15',
    null,
    'Hobby Overflow Discord',
    'joined',
    'accessible',
    'unknown',
    'in_app_browser',
    false,
    '#tournament-schedule, Magic #announcements, Magic #general',
    'Existing signed-in in-app browser Discord session',
    'manual_session',
    'medium',
    'occasional',
    'Useful for resolving Hobby Overflow source-health and schedule-time contradictions, especially whether the public late-night Commander row matches store-controlled Magic schedule evidence.',
    '2026-07-20',
    '2026-06-25',
    'Accepted pass 2 found Magic activity and an older March 2026 Thursday Magic schedule image, but not enough current evidence to rewrite event rows.'
  ),
  (
    'src-kng-discord-2026-07-14',
    null,
    'Krazy Nick''s Games Discord',
    'joined',
    'accessible',
    'unknown',
    'in_app_browser',
    false,
    '#events, #weekly-event-schedule, #commander, #limited',
    'Existing signed-in in-app browser Discord session',
    'manual_session',
    'high',
    'occasional',
    'Useful for Commander pod turnout, same-day go/no-go questions, power-level texture, and whether ad hoc Commander is worth a drive.',
    '2026-07-20',
    '2026-07-19',
    'Accepted pass 2 found useful Commander turnout and pod-formation texture, while schedule channels were sampled as stale.'
  ),
  (
    'src-kingslayer-discord-route-2026-07-18',
    '692870371157999626',
    'Kingslayer Games Discord',
    'joined',
    'accessible',
    'unknown',
    'in_app_browser',
    false,
    '#commander, #mtg-announcements, #fountain-valley-town-square',
    'Existing signed-in in-app browser Discord session',
    'manual_session',
    'high',
    'weekly',
    'High-value route for same-day Commander attendance, Fountain Valley versus Lake Forest branch texture, special-event displacement, draft/prerelease announcements, and go/no-go planning.',
    '2026-07-20',
    '2026-07-19',
    'Accepted pass 2 found current Commander coordination and recent multi-format MTG announcements. Branch-aware interpretation remains required.'
  ),
  (
    'src-paper-heros-discord-magic-hb-2026-07-20',
    '451625704723841024',
    'Paper Hero''s Games Discord',
    'joined',
    'accessible',
    'present',
    'in_app_browser',
    false,
    'Huntington Beach #magic-the-gathering',
    'Existing signed-in in-app browser Discord session',
    'manual_session',
    'high',
    'weekly',
    'High-value route for Huntington Beach Magic reminders, schedule changes, draft/Pauper/Standard leads, and later Commander/LFG texture if it appears.',
    '2026-07-20',
    '2026-07-11',
    'Accepted pass 2 captured the Huntington Beach Magic channel and added Pauper and draft rows. Standard remains event-TBD pending official/WPN calendar reconciliation.'
  )
on conflict (source_id) do update set
  server_id = excluded.server_id,
  server_name = excluded.server_name,
  access_state = excluded.access_state,
  content_access = excluded.content_access,
  role_gate = excluded.role_gate,
  preferred_access_surface = excluded.preferred_access_surface,
  user_action_required = excluded.user_action_required,
  known_internal_target = excluded.known_internal_target,
  last_successful_access_method = excluded.last_successful_access_method,
  automation_suitability = excluded.automation_suitability,
  route_value = excluded.route_value,
  monitoring_cadence = excluded.monitoring_cadence,
  monitoring_reason = excluded.monitoring_reason,
  last_checked = excluded.last_checked,
  last_useful_signal_at = excluded.last_useful_signal_at,
  notes = excluded.notes;

insert into public.discord_channel_watchlist (
  id,
  profile_source_id,
  channel_source_id,
  channel_id,
  channel_name,
  channel_url,
  channel_type,
  priority,
  cadence,
  reason_to_monitor,
  expected_signal_types,
  access_status,
  noise_level,
  last_checked,
  last_checked_at,
  last_seen_message_at,
  last_useful_signal_at,
  monitoring_status,
  notes
) values
  (
    'discord-watch-collectors-mtg-announcements-events',
    'src-collectors-discord-2026-07-14',
    'src-collectors-discord-2026-07-14',
    null,
    '#mtg-announcements-and-events',
    null,
    'announcements',
    'high',
    'weekly',
    'Capture current weekly lineup images, signup codes, casual versus optimized Commander separation, draft/special announcements, and same-day schedule changes.',
    array['event_opportunity', 'source_health', 'registration', 'operational'],
    'accessible',
    'low',
    '2026-07-20',
    null,
    null,
    '2026-07-19',
    'active',
    'Direct channel ID/URL was not preserved; recover it on the next map-driven check.'
  ),
  (
    'discord-watch-collectors-event-rules',
    'src-collectors-discord-2026-07-14',
    null,
    null,
    '#event-rules',
    null,
    'format',
    'medium',
    'occasional',
    'Preserve Commander rules, proxy policy, bracket expectations, and casual versus optimized separation.',
    array['venue_fit', 'proxy_policy', 'power_level'],
    'accessible',
    'low',
    '2026-07-20',
    null,
    null,
    '2026-07-14',
    'active',
    'Rules are stable enough for occasional checks unless Collectors changes Commander policy.'
  ),
  (
    'discord-watch-hobbyoverflow-tournament-schedule',
    'src-hobbyoverflow-discord-invite-2026-07-15',
    'src-hobbyoverflow-discord-invite-2026-07-15',
    null,
    '#tournament-schedule',
    null,
    'schedule',
    'high',
    'occasional',
    'Resolve whether current Magic/Commander times differ from WPN/app rows and catch updated schedule images.',
    array['source_health', 'event_opportunity'],
    'accessible',
    'low',
    '2026-07-20',
    null,
    null,
    '2026-03-23',
    'active',
    'March 2026 schedule image is useful context but too old to overwrite current event rows.'
  ),
  (
    'discord-watch-hobbyoverflow-magic-announcements',
    'src-hobbyoverflow-discord-invite-2026-07-15',
    null,
    null,
    'Magic #announcements',
    null,
    'announcements',
    'medium',
    'occasional',
    'Catch newer MTG-specific posts, special events, and evidence that resolves the Thursday Magic/Commander ambiguity.',
    array['event_opportunity', 'source_health'],
    'accessible',
    'low',
    '2026-07-20',
    null,
    null,
    '2026-06-25',
    'active',
    'Useful current-ish Magic activity, but no July correction from accepted pass 2.'
  ),
  (
    'discord-watch-krazy-commander',
    'src-kng-discord-2026-07-14',
    'src-kng-discord-2026-07-14',
    null,
    '#commander',
    null,
    'lfg',
    'high',
    'occasional',
    'Track whether Commander pods are firing, same-day attendance questions, power/proxy texture, and solo-arrival usefulness.',
    array['community_activity', 'venue_fit', 'proxy_policy'],
    'accessible',
    'medium',
    '2026-07-20',
    null,
    null,
    '2026-07-19',
    'active',
    'Accepted pass 2 found June two-pod confirmation and July ad hoc availability questions.'
  ),
  (
    'discord-watch-krazy-weekly-event-schedule',
    'src-kng-discord-2026-07-14',
    null,
    null,
    '#weekly-event-schedule',
    null,
    'schedule',
    'medium',
    'occasional',
    'Check whether stale schedule channels revive or contradict WPN/EventLink rows.',
    array['source_health', 'event_opportunity'],
    'accessible',
    'low',
    '2026-07-20',
    null,
    null,
    null,
    'active',
    'Sampled as stale in accepted pass 2; quiet/stale result does not erase route value.'
  ),
  (
    'discord-watch-kingslayer-commander',
    'src-kingslayer-discord-route-2026-07-18',
    'src-kingslayer-discord-route-2026-07-18',
    null,
    '#commander',
    null,
    'lfg',
    'high',
    'weekly',
    'Track same-day pod formation, Fountain Valley versus Lake Forest branch decisions, travel-worthiness, power texture, and solo-arrival usefulness.',
    array['community_activity', 'venue_fit', 'operational'],
    'accessible',
    'medium',
    '2026-07-20',
    null,
    null,
    '2026-07-19',
    'active',
    'Accepted pass 2 found current coordination around whether enough players existed to justify driving over.'
  ),
  (
    'discord-watch-kingslayer-mtg-announcements',
    'src-kingslayer-discord-route-2026-07-18',
    null,
    null,
    '#mtg-announcements',
    null,
    'announcements',
    'high',
    'weekly',
    'Capture multi-format Kingslayer announcements, prereleases, drafts, and branch-specific special-event displacement.',
    array['event_opportunity', 'registration', 'source_health'],
    'accessible',
    'low',
    '2026-07-20',
    null,
    null,
    '2026-06-18',
    'active',
    'Useful for all three Kingslayer stores; keep normalized findings branch-aware.'
  ),
  (
    'discord-watch-paper-heros-hb-magic',
    'src-paper-heros-discord-magic-hb-2026-07-20',
    'src-paper-heros-discord-magic-hb-2026-07-20',
    '1323064182660399184',
    'Huntington Beach #magic-the-gathering',
    'https://discord.com/channels/451625704723841024/1323064182660399184',
    'announcements',
    'high',
    'weekly',
    'Capture Huntington Beach Magic reminders, weekly Pauper/draft/Standard leads, schedule changes, and any Commander/LFG texture.',
    array['event_opportunity', 'registration', 'source_health', 'community_activity'],
    'accessible',
    'medium',
    '2026-07-20',
    null,
    null,
    '2026-07-11',
    'active',
    'Direct channel URL is known. Standard remains event-TBD until official/WPN calendar context is confirmed.'
  )
on conflict (id) do update set
  profile_source_id = excluded.profile_source_id,
  channel_source_id = excluded.channel_source_id,
  channel_id = excluded.channel_id,
  channel_name = excluded.channel_name,
  channel_url = excluded.channel_url,
  channel_type = excluded.channel_type,
  priority = excluded.priority,
  cadence = excluded.cadence,
  reason_to_monitor = excluded.reason_to_monitor,
  expected_signal_types = excluded.expected_signal_types,
  access_status = excluded.access_status,
  noise_level = excluded.noise_level,
  last_checked = excluded.last_checked,
  last_checked_at = excluded.last_checked_at,
  last_seen_message_at = excluded.last_seen_message_at,
  last_useful_signal_at = excluded.last_useful_signal_at,
  monitoring_status = excluded.monitoring_status,
  notes = excluded.notes;
