insert into public.discord_access_profiles (
  source_id, server_id, server_name, access_state, content_access, role_gate,
  preferred_access_surface, user_action_required, known_internal_target,
  last_successful_access_method, last_failed_access_method,
  automation_suitability, route_value, monitoring_cadence, monitoring_reason,
  last_checked, notes, safe_access_mode, safe_access_notes,
  preparatory_survey_completed_at, updated_at
)
values
  ('src-buddies-discord-2026-07-18', null, 'Buddies Collectibles', 'invite_gated', 'not_inspected', 'unknown', 'invite_link', false, null, null, 'Joining would be an account-side effect and is not justified for an optional texture source.', 'public_metadata_only', 'medium', 'paused', 'Existing WPN and store sources are sufficient; Discord texture is optional unless the user promotes Buddies for a visit.', date '2026-08-22', '[2026-08-22] Known route considered and terminally paused. Do not repeat preparatory surveying without a material new signal or explicit user request.', 'route_only_tbd', 'Official invite is preserved; no join was performed.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-coretcg-discord-route-2026-07-18', null, 'CoreTCG Tournament Discord', 'invite_gated', 'not_inspected', 'unknown', 'invite_link', false, null, null, 'Joining would be an account-side effect and is not justified for a low-priority personal-fit source.', 'public_metadata_only', 'low', 'paused', 'CoreTCG is already a low personal-fit venue with adequate WPN/store evidence.', date '2026-08-22', '[2026-08-22] Known route considered and terminally paused. Do not repeat preparatory surveying without materially different evidence.', 'route_only_tbd', 'Official invite is preserved; no join was performed.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-gxgamers-linktree-2026-07-18', null, 'GXGAMERS', 'public_only', 'not_inspected', 'unknown', 'public_page', false, null, null, 'The Linktree route does not justify deeper account-side access for a poor-fit venue.', 'public_metadata_only', 'low', 'paused', 'Existing evidence describes a no-proxy/high-power environment that is a poor default fit.', date '2026-08-22', '[2026-08-22] Discord route lead considered and terminally paused.', 'route_only_tbd', 'Discord remains a route behind the official Linktree; no join was performed.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-nextgen-discord-route-2026-07-18', null, 'Next-Gen Games', 'invite_gated', 'not_inspected', 'unknown', 'invite_link', false, null, null, 'Joining is unnecessary while broad current WPN and store-controlled event coverage answers planning needs.', 'public_metadata_only', 'medium', 'paused', 'Player texture is optional and should reopen only for a visit-driven decision or new material signal.', date '2026-08-22', '[2026-08-22] Known route considered and terminally paused.', 'route_only_tbd', 'Official invite is preserved; no join was performed.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-otaku-vault-discord-route-2026-07-18', null, 'Otaku Vault', 'public_only', 'not_inspected', 'unknown', 'public_page', false, null, null, 'The official-site route does not expose a safe mapped channel and the venue is low priority absent a relevant special event.', 'public_metadata_only', 'low', 'paused', 'Existing WPN and social coverage is sufficient for current planning.', date '2026-08-22', '[2026-08-22] Discord route lead considered and terminally paused.', 'route_only_tbd', 'Route is preserved through the official store surface; no join was performed.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-tilted-discord-route-2026-07-17', null, 'Tilted Gaming', 'invite_gated', 'not_inspected', 'unknown', 'invite_link', false, null, null, 'Joining is unnecessary unless the user is deciding on a visit and needs player-culture texture.', 'public_metadata_only', 'medium', 'paused', 'Current calendar and venue assessment are already sufficient for routine planning.', date '2026-08-22', '[2026-08-22] Known route considered and terminally paused.', 'route_only_tbd', 'Official invite is preserved; no join was performed.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-turnzero-discord-route-2026-07-18', null, 'Turn Zero Games', 'invite_gated', 'not_inspected', 'unknown', 'invite_link', false, null, null, 'Joining is unnecessary unless Canadian Highlander cadence or visit-specific player texture becomes material.', 'public_metadata_only', 'medium', 'paused', 'WPN and existing event sources are sufficient for routine planning.', date '2026-08-22', '[2026-08-22] Known route considered and terminally paused.', 'route_only_tbd', 'Official invite is preserved; no join was performed.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-collector-legion-discord-2026-07-14', null, 'Collector Legion', 'public_only', 'accessible', 'unknown', 'public_page', false, 'announcements, upcoming-events, MTG, edh-commander', '2026-07-14 bounded Discord baseline', null, 'manual_session', 'medium', 'paused', 'The baseline already captured useful EDH/LFG texture; current official and social monitoring is sufficient unless a new material Discord delta appears.', date '2026-08-22', '[2026-08-22] Existing baseline accepted as the completed preparatory survey; no recurring route added.', 'manual_open_required', 'Historical bounded content evidence is preserved; no current exact cloud route is required.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-spellhold-discord-2026-07-14', null, 'Spellhold Games', 'public_only', 'accessible', 'unknown', 'public_page', false, 'announcements, hours-and-event-schedule, MTG news, limited, EDH', '2026-07-14 bounded Discord baseline', null, 'manual_session', 'medium', 'paused', 'The baseline established image-heavy schedule corroboration but little coordination value; WPN/store sources are better recurring surfaces.', date '2026-08-22', '[2026-08-22] Existing baseline accepted as the completed preparatory survey; no recurring route added.', 'manual_open_required', 'Historical bounded content evidence is sufficient; avoid recurring image-flyer duplication.', timestamptz '2026-08-22 22:11:15+00', now()),
  ('src-guildhouse-discord-2026-07-14', null, 'The Guild House', 'public_only', 'accessible', 'unknown', 'public_page', false, 'announcements, table-reservations, general, collectible-card-game channels', '2026-07-14 bounded Discord baseline and refinement', null, 'manual_session', 'medium', 'paused', 'The baseline already confirmed Tuesday Commander and reservation logistics; current WPN, calendar, and social sources are sufficient recurring surfaces.', date '2026-08-22', '[2026-08-22] Existing baseline accepted as the completed preparatory survey; no recurring route added.', 'manual_open_required', 'Historical bounded content evidence is retained without duplicating stronger public monitoring.', timestamptz '2026-08-22 22:11:15+00', now())
on conflict (source_id) do update set
  monitoring_cadence = excluded.monitoring_cadence,
  monitoring_reason = excluded.monitoring_reason,
  notes = excluded.notes,
  safe_access_mode = excluded.safe_access_mode,
  safe_access_notes = excluded.safe_access_notes,
  preparatory_survey_completed_at = excluded.preparatory_survey_completed_at,
  updated_at = now();
